# NIR White Lagkitan Corn (Binary-Class)

In [1]:
import pandas as pd
import numpy as np

## Load Data

In [2]:
df_raw_data = pd.read_csv('appendix_raw_dataset2.csv')
df_raw_data

,Class,730nm,760nm,810nm,860nm,900nm,940nm,Brix (%),Sample No.
0,Not Sweet,223.095184,153.247070,308.192169,1929.094238,88.592545,43.446762,6.4,1
1,Not Sweet,225.528946,155.787079,315.297485,1996.374756,90.668930,43.446762,6.4,1
2,Not Sweet,213.360123,154.940414,306.415863,2071.775391,86.516159,43.446762,6.4,1
3,Not Sweet,197.946274,147.320389,278.882843,2032.334961,81.671249,38.509628,6.4,1
4,Not Sweet,247.432846,177.800476,350.823944,2400.057617,90.668930,40.484482,6.4,1
...,...,...,...,...,...,...,...,...,...
4155,Sweet,244.999069,174.413788,367.699036,2205.176270,131.504562,51.346172,9.4,130
4156,Sweet,244.999069,174.413788,352.600281,2121.655518,121.814751,51.346172,9.4,130
4157,Sweet,249.866608,175.260468,365.034546,2181.976074,128.043915,55.295879,9.4,130
4158,Sweet,238.509033,171.027115,349.047638,2133.255615,120.430489,52.333599,9.4,130
4159,Sweet,266.902954,178.647141,360.593719,2205.176270,121.814751,50.358746,9.4,130

## Preprocessing

In [3]:
feature_cols = ['730nm','760nm','810nm','860nm','900nm','940nm']

### Outlier Removal

In [4]:
def filter_scans_stage1(df, keep_ratio_fallback=0.85):
    filtered_parts = []

    for sample_id, group in df.groupby('Sample No.'):
        X = group[feature_cols].values

        centroid = X.mean(axis=0)

        dists = np.linalg.norm(X - centroid, axis=1)

        med = np.median(dists)
        mad = np.median(np.abs(dists - med))

        threshold = med + 1.5 * mad

        mask = dists <= threshold

        if mask.sum() < len(group) * 0.5:
            cutoff = np.quantile(dists, keep_ratio_fallback)
            mask = dists <= cutoff

        filtered_group = group[mask]
        filtered_parts.append(filtered_group)

    return pd.concat(filtered_parts, ignore_index=True)

df_stage1 = filter_scans_stage1(df_raw_data)

### SNV

In [5]:
df_snv = df_stage1.copy()

def snv_row(x):
    x = x.astype(float)
    mean = x.mean()
    std = x.std(ddof=1)

    if std < 1e-8:
        return x * np.nan

    return (x - mean) / std

df_snv[feature_cols] = df_snv[feature_cols].apply(
    snv_row, axis=1, result_type='expand'
)

df_snv = df_snv.dropna()

### Median Aggregation

In [6]:
def stage2_median_aggregation(df):

    df_agg = df.groupby('Sample No.')[feature_cols].median().reset_index()

    class_map = df.groupby('Sample No.')['Class'].first().reset_index()

    df_final = pd.merge(df_agg, class_map, on='Sample No.')

    return df_final

df_stage2 = stage2_median_aggregation(df_snv)

## Data Preparation

### Selecting Features (X) and Targets (y)

In [10]:
X = df_stage2[feature_cols]
y = df_stage2['Class']

### Encode Labels

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [14]:
dict(zip(le.classes_, le.transform(le.classes_)))

{'Not Sweet': np.int64(0), 'Sweet': np.int64(1)}

### Data Split

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(X, y_encoded, test_size=0.3, stratify=y_encoded, random_state=42)
X_val, X_test, y_val , y_test = train_test_split(X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42)

## Optuna Hyperparameter Tuning

In [16]:
import optuna
from sklearn.model_selection import cross_val_score, RepeatedStratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
from xgboost import XGBClassifier

# For reproducibility
sampler = optuna.samplers.TPESampler(seed=42)
inner_cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=42)

# Tune to penalize instability
alpha = 0.5
stability_std_cap = 0.02

C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Logistic Regression

In [17]:
def objective_lr(trial):
    params = {
        'C': trial.suggest_float('C', 0.05, 3.0, log=True),

        'penalty': 'l2',

        'solver': trial.suggest_categorical(
            'solver', ['liblinear', 'lbfgs']
        ),

        'class_weight': trial.suggest_categorical(
            'class_weight', ['balanced', None]
        ),

        'max_iter': 5000,
        'tol': trial.suggest_float('tol', 1e-5, 1e-3, log=True),
        'random_state': 42
    }

    model = Pipeline([
        ('scaler', StandardScaler()),
        ('clf', LogisticRegression(**params))
    ])

    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=inner_cv,
        scoring='roc_auc'
    )

    mean_score = score.mean()
    std_score = score.std()

    return mean_score - alpha * min(std_score, stability_std_cap)

In [18]:
study_lr = optuna.create_study(direction='maximize', sampler=sampler)
study_lr.optimize(objective_lr, n_trials=100)

study_lr.best_params, study_lr.best_value

[I 2026-07-28 18:48:57,729] A new study created in memory with name: no-name-50a76009-f66a-43ec-a13a-7a0089e964a3
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
[I 2026-07-28 18:48:57,963] Trial 0 finished with value: 0.5789999999999998 and parameters: {'C': 0.23171758042400847, 'solver': 'liblinear', 'class_weight': 'balanced', 'tol': 2.0511104188433963e-05}. Best is trial 0 with value: 0.5789999999999998.
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

({'C': 0.5168899683396826,
  'solver': 'liblinear',
  'class_weight': None,
  'tol': 0.0007145407933214536},
 0.5873333333333333)

### Random Forest

In [19]:
def objective_rf(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 150, 350),

        'max_depth': trial.suggest_int('max_depth', 2, 5),

        'max_features': trial.suggest_categorical(
            'max_features', ['sqrt', 0.5]
        ),

        'min_samples_split': trial.suggest_int('min_samples_split', 5, 15),

        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 2, 8),

        'max_leaf_nodes': trial.suggest_int('max_leaf_nodes', 8, 25),

        'class_weight': trial.suggest_categorical(
            'class_weight', ['balanced', None]
        ),

        'bootstrap': True,
        'n_jobs': -1,
        'random_state': 42
    }

    model = Pipeline([
        ('clf', RandomForestClassifier(**params))
    ])

    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=inner_cv,
        scoring='roc_auc'
    )

    mean_score = score.mean()
    std_score = score.std()

    return mean_score - alpha * min(std_score, stability_std_cap)

In [20]:
study_rf = optuna.create_study(direction='maximize', sampler=sampler)
study_rf.optimize(objective_rf, n_trials=100)

study_rf.best_params, study_rf.best_value

[I 2026-07-28 18:49:49,879] A new study created in memory with name: no-name-864a451c-3d18-4145-a9eb-335a0d2bbcd3
[I 2026-07-28 18:50:10,193] Trial 0 finished with value: 0.4943333333333334 and parameters: {'n_estimators': 228, 'max_depth': 3, 'max_features': 'sqrt', 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_leaf_nodes': 10, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.4943333333333334.
[I 2026-07-28 18:50:37,906] Trial 1 finished with value: 0.482 and parameters: {'n_estimators': 348, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 13, 'min_samples_leaf': 6, 'max_leaf_nodes': 21, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.4943333333333334.
[I 2026-07-28 18:50:57,902] Trial 2 finished with value: 0.5346666666666666 and parameters: {'n_estimators': 222, 'max_depth': 2, 'max_features': 'sqrt', 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_leaf_nodes': 13, 'class_weight': None}. Best is trial 2 with value: 0.5346666666666666.
[I 2026-07-28 18:51:14,547] Trial 3 finished with value: 0.4620000000000001 and parameters: {'n_estimators': 278, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_leaf_nodes': 18, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.5346666666666666.
[I 2026-07-28 18:51:27,988] Trial 4 finished with value: 0.47866666666666663 and parameters: {'n_estimators': 255, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_leaf_nodes': 13, 'class_weight': None}. Best is trial 2 with value: 0.5346666666666666.
[I 2026-07-28 18:51:43,723] Trial 5 finished with value: 0.5156666666666667 and parameters: {'n_estimators': 200, 'max_depth': 3, 'max_features': 'sqrt', 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_leaf_nodes': 10, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.5346666666666666.
[I 2026-07-28 18:51:57,508] Trial 6 finished with value: 0.4916666666666666 and parameters: {'n_estimators': 277, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 14, 'min_samples_leaf': 5, 'max_leaf_nodes': 22, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.5346666666666666.
[I 2026-07-28 18:52:13,988] Trial 7 finished with value: 0.5386666666666665 and parameters: {'n_estimators': 172, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_leaf_nodes': 17, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.5386666666666665.
[I 2026-07-28 18:52:23,000] Trial 8 finished with value: 0.47533333333333333 and parameters: {'n_estimators': 174, 'max_depth': 3, 'max_features': 'sqrt', 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_leaf_nodes': 14, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.5386666666666665.
[I 2026-07-28 18:52:33,046] Trial 9 finished with value: 0.4746666666666666 and parameters: {'n_estimators': 200, 'max_depth': 3, 'max_features': 'sqrt', 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_leaf_nodes': 17, 'class_weight': None}. Best is trial 7 with value: 0.5386666666666665.
[I 2026-07-28 18:52:40,795] Trial 10 finished with value: 0.5489999999999999 and parameters: {'n_estimators': 150, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_leaf_nodes': 25, 'class_weight': None}. Best is trial 10 with value: 0.5489999999999999.
[I 2026-07-28 18:52:54,151] Trial 11 finished with value: 0.5506666666666665 and parameters: {'n_estimators': 153, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_leaf_nodes': 25, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:53:08,265] Trial 12 finished with value: 0.5473333333333331 and parameters: {'n_estimators': 152, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_leaf_nodes': 25, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:53:19,587] Trial 13 finished with value: 0.5376666666666666 and parameters: {'n_estimators': 156, 'max_depth': 4, 'max_features': 0.5, 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_leaf_nodes': 25, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:53:40,359] Trial 14 finished with value: 0.5323333333333333 and parameters: {'n_estimators': 326, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_leaf_nodes': 22, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:53:54,764] Trial 15 finished with value: 0.5399999999999999 and parameters: {'n_estimators': 192, 'max_depth': 4, 'max_features': 0.5, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_leaf_nodes': 20, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:54:08,313] Trial 16 finished with value: 0.4706666666666666 and parameters: {'n_estimators': 152, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_leaf_nodes': 24, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:54:28,381] Trial 17 finished with value: 0.5173333333333333 and parameters: {'n_estimators': 225, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 15, 'min_samples_leaf': 4, 'max_leaf_nodes': 23, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:54:42,869] Trial 18 finished with value: 0.5103333333333334 and parameters: {'n_estimators': 186, 'max_depth': 4, 'max_features': 0.5, 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_leaf_nodes': 25, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:54:56,155] Trial 19 finished with value: 0.534 and parameters: {'n_estimators': 247, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_leaf_nodes': 19, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:55:05,258] Trial 20 finished with value: 0.5413333333333333 and parameters: {'n_estimators': 170, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_leaf_nodes': 8, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:55:13,880] Trial 21 finished with value: 0.5423333333333332 and parameters: {'n_estimators': 158, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_leaf_nodes': 25, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:55:22,065] Trial 22 finished with value: 0.5489999999999998 and parameters: {'n_estimators': 151, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_leaf_nodes': 23, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:55:31,813] Trial 23 finished with value: 0.5456666666666666 and parameters: {'n_estimators': 181, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_leaf_nodes': 23, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:55:44,297] Trial 24 finished with value: 0.5389999999999998 and parameters: {'n_estimators': 210, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_leaf_nodes': 23, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:55:53,511] Trial 25 finished with value: 0.5273333333333333 and parameters: {'n_estimators': 164, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_leaf_nodes': 21, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:56:09,953] Trial 26 finished with value: 0.5273333333333332 and parameters: {'n_estimators': 304, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_leaf_nodes': 24, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:56:18,099] Trial 27 finished with value: 0.5469999999999999 and parameters: {'n_estimators': 150, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_leaf_nodes': 20, 'class_weight': None}. Best is trial 11 with value: 0.5506666666666665.
[I 2026-07-28 18:56:27,637] Trial 28 finished with value: 0.5506666666666666 and parameters: {'n_estimators': 184, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_leaf_nodes': 22, 'class_weight': None}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:56:38,991] Trial 29 finished with value: 0.5429999999999998 and parameters: {'n_estimators': 211, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_leaf_nodes': 21, 'class_weight': None}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:56:52,130] Trial 30 finished with value: 0.5183333333333333 and parameters: {'n_estimators': 247, 'max_depth': 4, 'max_features': 0.5, 'min_samples_split': 11, 'min_samples_leaf': 4, 'max_leaf_nodes': 15, 'class_weight': None}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:57:01,811] Trial 31 finished with value: 0.5489999999999998 and parameters: {'n_estimators': 178, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_leaf_nodes': 24, 'class_weight': None}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:57:10,896] Trial 32 finished with value: 0.5443333333333333 and parameters: {'n_estimators': 167, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_leaf_nodes': 22, 'class_weight': None}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:57:20,705] Trial 33 finished with value: 0.5469999999999999 and parameters: {'n_estimators': 184, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_leaf_nodes': 23, 'class_weight': None}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:57:29,540] Trial 34 finished with value: 0.5183333333333333 and parameters: {'n_estimators': 165, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 5, 'max_leaf_nodes': 24, 'class_weight': 'balanced'}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:57:40,022] Trial 35 finished with value: 0.5423333333333332 and parameters: {'n_estimators': 193, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_leaf_nodes': 20, 'class_weight': None}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:57:49,449] Trial 36 finished with value: 0.5276666666666665 and parameters: {'n_estimators': 163, 'max_depth': 2, 'max_features': 'sqrt', 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_leaf_nodes': 22, 'class_weight': None}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:58:00,212] Trial 37 finished with value: 0.5503333333333332 and parameters: {'n_estimators': 200, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_leaf_nodes': 25, 'class_weight': 'balanced'}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:58:11,335] Trial 38 finished with value: 0.517 and parameters: {'n_estimators': 215, 'max_depth': 3, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_leaf_nodes': 25, 'class_weight': 'balanced'}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:58:23,689] Trial 39 finished with value: 0.5 and parameters: {'n_estimators': 236, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 12, 'min_samples_leaf': 5, 'max_leaf_nodes': 11, 'class_weight': 'balanced'}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:58:38,580] Trial 40 finished with value: 0.5306666666666666 and parameters: {'n_estimators': 274, 'max_depth': 4, 'max_features': 'sqrt', 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_leaf_nodes': 24, 'class_weight': 'balanced'}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:58:49,305] Trial 41 finished with value: 0.5383333333333332 and parameters: {'n_estimators': 202, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_leaf_nodes': 23, 'class_weight': 'balanced'}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:58:58,729] Trial 42 finished with value: 0.5366666666666666 and parameters: {'n_estimators': 174, 'max_depth': 5, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_leaf_nodes': 21, 'class_weight': 'balanced'}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:59:08,919] Trial 43 finished with value: 0.5433333333333332 and parameters: {'n_estimators': 192, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_leaf_nodes': 25, 'class_weight': 'balanced'}. Best is trial 28 with value: 0.5506666666666666.
[I 2026-07-28 18:59:18,645] Trial 44 finished with value: 0.5539999999999999 and parameters: {'n_estimators': 161, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_leaf_nodes': 18, 'class_weight': 'balanced'}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 18:59:28,125] Trial 45 finished with value: 0.5476666666666665 and parameters: {'n_estimators': 176, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_leaf_nodes': 18, 'class_weight': 'balanced'}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 18:59:44,291] Trial 46 finished with value: 0.4706666666666666 and parameters: {'n_estimators': 350, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 13, 'min_samples_leaf': 7, 'max_leaf_nodes': 19, 'class_weight': 'balanced'}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 18:59:53,302] Trial 47 finished with value: 0.5053333333333333 and parameters: {'n_estimators': 160, 'max_depth': 3, 'max_features': 'sqrt', 'min_samples_split': 15, 'min_samples_leaf': 4, 'max_leaf_nodes': 15, 'class_weight': 'balanced'}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:00:03,612] Trial 48 finished with value: 0.5343333333333332 and parameters: {'n_estimators': 201, 'max_depth': 4, 'max_features': 0.5, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_leaf_nodes': 16, 'class_weight': 'balanced'}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:00:13,029] Trial 49 finished with value: 0.5353333333333333 and parameters: {'n_estimators': 187, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_leaf_nodes': 24, 'class_weight': 'balanced'}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:00:22,592] Trial 50 finished with value: 0.5436666666666666 and parameters: {'n_estimators': 171, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_leaf_nodes': 12, 'class_weight': 'balanced'}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:00:30,194] Trial 51 finished with value: 0.5493333333333332 and parameters: {'n_estimators': 152, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_leaf_nodes': 25, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:00:37,801] Trial 52 finished with value: 0.5509999999999999 and parameters: {'n_estimators': 157, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_leaf_nodes': 25, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:00:46,007] Trial 53 finished with value: 0.5493333333333332 and parameters: {'n_estimators': 159, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_leaf_nodes': 25, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:00:53,626] Trial 54 finished with value: 0.5506666666666665 and parameters: {'n_estimators': 158, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_leaf_nodes': 22, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:01:02,214] Trial 55 finished with value: 0.5456666666666666 and parameters: {'n_estimators': 178, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_leaf_nodes': 22, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:01:11,109] Trial 56 finished with value: 0.5133333333333333 and parameters: {'n_estimators': 168, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 13, 'min_samples_leaf': 5, 'max_leaf_nodes': 19, 'class_weight': 'balanced'}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:01:19,476] Trial 57 finished with value: 0.5299999999999999 and parameters: {'n_estimators': 159, 'max_depth': 3, 'max_features': 'sqrt', 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_leaf_nodes': 18, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:01:33,009] Trial 58 finished with value: 0.5323333333333333 and parameters: {'n_estimators': 263, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 13, 'min_samples_leaf': 4, 'max_leaf_nodes': 21, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:01:42,764] Trial 59 finished with value: 0.5323333333333333 and parameters: {'n_estimators': 194, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_leaf_nodes': 24, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:02:00,021] Trial 60 finished with value: 0.5266666666666667 and parameters: {'n_estimators': 339, 'max_depth': 4, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 4, 'max_leaf_nodes': 22, 'class_weight': 'balanced'}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:02:07,922] Trial 61 finished with value: 0.5506666666666665 and parameters: {'n_estimators': 150, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_leaf_nodes': 25, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:02:15,456] Trial 62 finished with value: 0.5526666666666666 and parameters: {'n_estimators': 156, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_leaf_nodes': 24, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:02:23,814] Trial 63 finished with value: 0.5526666666666666 and parameters: {'n_estimators': 156, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_leaf_nodes': 23, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:02:32,860] Trial 64 finished with value: 0.5473333333333333 and parameters: {'n_estimators': 157, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_leaf_nodes': 23, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:02:42,498] Trial 65 finished with value: 0.5489999999999999 and parameters: {'n_estimators': 168, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_leaf_nodes': 24, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.
[I 2026-07-28 19:02:50,956] Trial 66 finished with value: 0.5506666666666665 and parameters: {'n_estimators': 156, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_leaf_nodes': 23, 'class_weight': None}. Best is trial 44 with value: 0.5539999999999999.

({'n_estimators': 150,
  'max_depth': 2,
  'max_features': 0.5,
  'min_samples_split': 14,
  'min_samples_leaf': 3,
  'max_leaf_nodes': 13,
  'class_weight': None},
 0.5556666666666666)

### Linear Discriminant Analysis

In [21]:
def objective_lda(trial):
    solver = trial.suggest_categorical('solver', ['lsqr', 'eigen'])

    params = {
        'solver': solver,

        'shrinkage': trial.suggest_float(
            'shrinkage',
            0.05, 0.8,
            log=True
        ),

        'store_covariance': False
    }

    model = Pipeline([
        ('scaler', StandardScaler()),
        ('clf', LinearDiscriminantAnalysis(**params))
    ])

    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=inner_cv,
        scoring='roc_auc'
    )

    mean_score = score.mean()
    std_score = score.std()

    return mean_score - alpha * min(std_score, stability_std_cap)

In [22]:
study_lda = optuna.create_study(direction='maximize', sampler=sampler)
study_lda.optimize(objective_lda, n_trials=100)

study_lda.best_params, study_lda.best_value

[I 2026-07-28 19:07:49,734] A new study created in memory with name: no-name-521a3573-b087-4c1a-b32b-359add9b650d
[I 2026-07-28 19:07:50,083] Trial 0 finished with value: 0.5809999999999998 and parameters: {'solver': 'lsqr', 'shrinkage': 0.07472067993851027}. Best is trial 0 with value: 0.5809999999999998.
[I 2026-07-28 19:07:50,410] Trial 1 finished with value: 0.5856666666666666 and parameters: {'solver': 'eigen', 'shrinkage': 0.0978213368435106}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:50,698] Trial 2 finished with value: 0.5856666666666666 and parameters: {'solver': 'eigen', 'shrinkage': 0.09663047618134958}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:50,995] Trial 3 finished with value: 0.5709999999999998 and parameters: {'solver': 'lsqr', 'shrinkage': 0.28863041253831084}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:51,240] Trial 4 finished with value: 0.5823333333333333 and parameters: {'solver': 'lsqr', 'shrinkage': 0.06422287165850053}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:51,474] Trial 5 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.08386112223118043}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:51,739] Trial 6 finished with value: 0.5696666666666665 and parameters: {'solver': 'eigen', 'shrinkage': 0.3272192101274494}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:52,034] Trial 7 finished with value: 0.5839999999999999 and parameters: {'solver': 'eigen', 'shrinkage': 0.09369104721775232}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:52,296] Trial 8 finished with value: 0.5713333333333332 and parameters: {'solver': 'lsqr', 'shrinkage': 0.339579872987949}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:52,559] Trial 9 finished with value: 0.5793333333333334 and parameters: {'solver': 'eigen', 'shrinkage': 0.07320853585714257}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:52,799] Trial 10 finished with value: 0.5563333333333333 and parameters: {'solver': 'eigen', 'shrinkage': 0.6692876835393398}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:53,053] Trial 11 finished with value: 0.5836666666666664 and parameters: {'solver': 'eigen', 'shrinkage': 0.13858839209526258}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:53,299] Trial 12 finished with value: 0.5823333333333331 and parameters: {'solver': 'eigen', 'shrinkage': 0.14853343498327284}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:53,527] Trial 13 finished with value: 0.584 and parameters: {'solver': 'eigen', 'shrinkage': 0.05173408853765708}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:53,781] Trial 14 finished with value: 0.5803333333333331 and parameters: {'solver': 'eigen', 'shrinkage': 0.12860162374013662}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:54,058] Trial 15 finished with value: 0.5789999999999998 and parameters: {'solver': 'eigen', 'shrinkage': 0.20918291391055222}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:54,313] Trial 16 finished with value: 0.5806666666666667 and parameters: {'solver': 'eigen', 'shrinkage': 0.11100846024304432}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:54,566] Trial 17 finished with value: 0.5823333333333331 and parameters: {'solver': 'eigen', 'shrinkage': 0.20514373536544814}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:54,835] Trial 18 finished with value: 0.5823333333333333 and parameters: {'solver': 'eigen', 'shrinkage': 0.050461635030618374}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:55,070] Trial 19 finished with value: 0.5823333333333331 and parameters: {'solver': 'eigen', 'shrinkage': 0.16206462171801378}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:55,300] Trial 20 finished with value: 0.5839999999999999 and parameters: {'solver': 'eigen', 'shrinkage': 0.09951519298342686}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:55,523] Trial 21 finished with value: 0.5823333333333333 and parameters: {'solver': 'eigen', 'shrinkage': 0.050427226539833864}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:55,758] Trial 22 finished with value: 0.5823333333333333 and parameters: {'solver': 'eigen', 'shrinkage': 0.06343264313700023}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:55,986] Trial 23 finished with value: 0.5806666666666667 and parameters: {'solver': 'eigen', 'shrinkage': 0.10839756894305136}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:56,274] Trial 24 finished with value: 0.5823333333333333 and parameters: {'solver': 'eigen', 'shrinkage': 0.061901618768797795}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:56,501] Trial 25 finished with value: 0.568 and parameters: {'solver': 'eigen', 'shrinkage': 0.5066772613027338}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:56,733] Trial 26 finished with value: 0.5836666666666664 and parameters: {'solver': 'lsqr', 'shrinkage': 0.17143248707040473}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:56,968] Trial 27 finished with value: 0.5756666666666665 and parameters: {'solver': 'eigen', 'shrinkage': 0.2544548647713464}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:57,228] Trial 28 finished with value: 0.5819999999999999 and parameters: {'solver': 'eigen', 'shrinkage': 0.12125400348100468}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:57,477] Trial 29 finished with value: 0.5823333333333333 and parameters: {'solver': 'lsqr', 'shrinkage': 0.07876938577703146}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:57,711] Trial 30 finished with value: 0.5839999999999999 and parameters: {'solver': 'eigen', 'shrinkage': 0.0886727239723626}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:57,936] Trial 31 finished with value: 0.5823333333333333 and parameters: {'solver': 'lsqr', 'shrinkage': 0.07817899411675369}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:58,177] Trial 32 finished with value: 0.584 and parameters: {'solver': 'lsqr', 'shrinkage': 0.05857883873105383}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:58,531] Trial 33 finished with value: 0.584 and parameters: {'solver': 'lsqr', 'shrinkage': 0.05828800541175124}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:58,805] Trial 34 finished with value: 0.581 and parameters: {'solver': 'lsqr', 'shrinkage': 0.07001140789327245}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:59,031] Trial 35 finished with value: 0.584 and parameters: {'solver': 'lsqr', 'shrinkage': 0.056396990659355335}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:59,306] Trial 36 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.08870335934278445}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:59,527] Trial 37 finished with value: 0.5806666666666667 and parameters: {'solver': 'lsqr', 'shrinkage': 0.06522045258868647}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:07:59,771] Trial 38 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.10258160589357529}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:00,032] Trial 39 finished with value: 0.5809999999999998 and parameters: {'solver': 'eigen', 'shrinkage': 0.0746582811288235}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:00,300] Trial 40 finished with value: 0.584 and parameters: {'solver': 'lsqr', 'shrinkage': 0.055015122085222606}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:00,587] Trial 41 finished with value: 0.584 and parameters: {'solver': 'lsqr', 'shrinkage': 0.05884478652078909}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:00,865] Trial 42 finished with value: 0.5793333333333334 and parameters: {'solver': 'lsqr', 'shrinkage': 0.07190477896712494}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:01,098] Trial 43 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.08860238845762056}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:01,352] Trial 44 finished with value: 0.584 and parameters: {'solver': 'lsqr', 'shrinkage': 0.05101220166179296}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:01,634] Trial 45 finished with value: 0.5823333333333333 and parameters: {'solver': 'lsqr', 'shrinkage': 0.061829615618037834}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:01,873] Trial 46 finished with value: 0.581 and parameters: {'solver': 'eigen', 'shrinkage': 0.06735125259415979}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:02,117] Trial 47 finished with value: 0.5823333333333333 and parameters: {'solver': 'eigen', 'shrinkage': 0.08034735494649405}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:02,346] Trial 48 finished with value: 0.5836666666666664 and parameters: {'solver': 'eigen', 'shrinkage': 0.12039918847233305}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:02,557] Trial 49 finished with value: 0.5823333333333331 and parameters: {'solver': 'lsqr', 'shrinkage': 0.17445608702872586}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:02,846] Trial 50 finished with value: 0.584 and parameters: {'solver': 'eigen', 'shrinkage': 0.05624525013408634}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:03,094] Trial 51 finished with value: 0.584 and parameters: {'solver': 'lsqr', 'shrinkage': 0.05604259281479407}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:03,328] Trial 52 finished with value: 0.5823333333333333 and parameters: {'solver': 'lsqr', 'shrinkage': 0.05000911790602313}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:03,543] Trial 53 finished with value: 0.5836666666666664 and parameters: {'solver': 'lsqr', 'shrinkage': 0.1363787787302812}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:03,765] Trial 54 finished with value: 0.5856666666666666 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09849427392632748}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:03,997] Trial 55 finished with value: 0.5856666666666666 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09597433447768855}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:04,239] Trial 56 finished with value: 0.5839999999999999 and parameters: {'solver': 'eigen', 'shrinkage': 0.10146192022330382}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:04,468] Trial 57 finished with value: 0.5823333333333331 and parameters: {'solver': 'eigen', 'shrinkage': 0.1138575912726718}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:04,706] Trial 58 finished with value: 0.5839999999999999 and parameters: {'solver': 'eigen', 'shrinkage': 0.09303226241369679}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:04,951] Trial 59 finished with value: 0.5823333333333331 and parameters: {'solver': 'lsqr', 'shrinkage': 0.13999622699625286}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:05,183] Trial 60 finished with value: 0.5679999999999998 and parameters: {'solver': 'eigen', 'shrinkage': 0.4276566505310058}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:05,402] Trial 61 finished with value: 0.581 and parameters: {'solver': 'lsqr', 'shrinkage': 0.06898174045603436}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:05,629] Trial 62 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.08380527886886285}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:05,846] Trial 63 finished with value: 0.5823333333333331 and parameters: {'solver': 'lsqr', 'shrinkage': 0.15160819250647933}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:06,075] Trial 64 finished with value: 0.5856666666666666 and parameters: {'solver': 'lsqr', 'shrinkage': 0.0976163086331033}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:06,308] Trial 65 finished with value: 0.5856666666666666 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09875600369131265}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:06,537] Trial 66 finished with value: 0.5803333333333331 and parameters: {'solver': 'eigen', 'shrinkage': 0.12643493280336132}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:06,938] Trial 67 finished with value: 0.5756666666666665 and parameters: {'solver': 'lsqr', 'shrinkage': 0.23173891029210616}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:07,231] Trial 68 finished with value: 0.5823333333333331 and parameters: {'solver': 'eigen', 'shrinkage': 0.11247137730640146}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:07,488] Trial 69 finished with value: 0.5856666666666666 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09648114323505766}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:07,734] Trial 70 finished with value: 0.5856666666666666 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09723291594198404}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:07,971] Trial 71 finished with value: 0.5856666666666666 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09568941568014654}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:08,351] Trial 72 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.10326101873306402}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:08,609] Trial 73 finished with value: 0.5806666666666667 and parameters: {'solver': 'lsqr', 'shrinkage': 0.11028705154832585}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:08,994] Trial 74 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09405920766886884}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:09,344] Trial 75 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.08431935791658816}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:09,610] Trial 76 finished with value: 0.5836666666666664 and parameters: {'solver': 'lsqr', 'shrinkage': 0.11956573549527738}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:09,862] Trial 77 finished with value: 0.5349999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.747135165219051}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:10,091] Trial 78 finished with value: 0.5836666666666664 and parameters: {'solver': 'lsqr', 'shrinkage': 0.13446367187318709}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:10,326] Trial 79 finished with value: 0.5806666666666667 and parameters: {'solver': 'lsqr', 'shrinkage': 0.1070484753787914}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:10,591] Trial 80 finished with value: 0.5823333333333333 and parameters: {'solver': 'lsqr', 'shrinkage': 0.07694440719272264}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:10,896] Trial 81 finished with value: 0.5856666666666666 and parameters: {'solver': 'lsqr', 'shrinkage': 0.094850669801969}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:11,149] Trial 82 finished with value: 0.5823333333333333 and parameters: {'solver': 'lsqr', 'shrinkage': 0.08208198554998725}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:11,449] Trial 83 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09286392966206007}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:11,737] Trial 84 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09933042358354795}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:11,987] Trial 85 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.08668457007169772}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:12,249] Trial 86 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.11525109378253916}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:12,574] Trial 87 finished with value: 0.5856666666666666 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09648184212599786}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:12,839] Trial 88 finished with value: 0.5803333333333331 and parameters: {'solver': 'lsqr', 'shrinkage': 0.12831878082289616}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:13,085] Trial 89 finished with value: 0.5806666666666667 and parameters: {'solver': 'lsqr', 'shrinkage': 0.10470363587272055}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:13,333] Trial 90 finished with value: 0.5809999999999998 and parameters: {'solver': 'lsqr', 'shrinkage': 0.07534695696053861}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:13,587] Trial 91 finished with value: 0.5856666666666666 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09789595193688314}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:13,866] Trial 92 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09138512791767119}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:14,127] Trial 93 finished with value: 0.5839999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.08702474223203333}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:14,382] Trial 94 finished with value: 0.5806666666666667 and parameters: {'solver': 'lsqr', 'shrinkage': 0.10633346934525094}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:14,720] Trial 95 finished with value: 0.5823333333333333 and parameters: {'solver': 'lsqr', 'shrinkage': 0.07983982524697132}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:15,029] Trial 96 finished with value: 0.5823333333333331 and parameters: {'solver': 'lsqr', 'shrinkage': 0.14672998406610627}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:15,316] Trial 97 finished with value: 0.5819999999999999 and parameters: {'solver': 'lsqr', 'shrinkage': 0.1219818275366057}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:15,583] Trial 98 finished with value: 0.5793333333333334 and parameters: {'solver': 'eigen', 'shrinkage': 0.07314593698265605}. Best is trial 1 with value: 0.5856666666666666.
[I 2026-07-28 19:08:15,852] Trial 99 finished with value: 0.5856666666666666 and parameters: {'solver': 'lsqr', 'shrinkage': 0.09597847262048387}. Best is trial 1 with value: 0.5856666666666666.

({'solver': 'eigen', 'shrinkage': 0.0978213368435106}, 0.5856666666666666)

### Support Vector Machine

In [23]:
def objective_svc(trial):
    kernel = trial.suggest_categorical('kernel', ['linear', 'rbf'])

    C = trial.suggest_float('C', 0.05, 5.0, log=True)

    params = {
        'C': C,
        'kernel': kernel,
        'class_weight': trial.suggest_categorical(
            'class_weight', ['balanced', None]
        ),
    }

    if kernel == 'rbf':
        params['gamma'] = trial.suggest_float(
            'gamma',
            1e-4,
            0.01,
            log=True
        )

    model = Pipeline([
        ('scaler', StandardScaler()),
        ('clf', SVC(**params))
    ])

    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=inner_cv,
        scoring='roc_auc'
    )

    mean_score = score.mean()
    std_score = score.std()

    return mean_score - alpha * min(std_score, stability_std_cap)

In [24]:
study_svc = optuna.create_study(direction='maximize', sampler=sampler)
study_svc.optimize(objective_svc, n_trials=100)

study_svc.best_params, study_svc.best_value

[I 2026-07-28 19:08:15,913] A new study created in memory with name: no-name-d99bfee9-4644-4993-be8c-a11423d8ae5e
[I 2026-07-28 19:08:16,192] Trial 0 finished with value: 0.5640000000000001 and parameters: {'kernel': 'linear', 'C': 3.5347380986089947, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.5640000000000001.
[I 2026-07-28 19:08:16,426] Trial 1 finished with value: 0.5143333333333333 and parameters: {'kernel': 'rbf', 'C': 0.644720719653709, 'class_weight': 'balanced', 'gamma': 0.00015353434324857047}. Best is trial 0 with value: 0.5640000000000001.
[I 2026-07-28 19:08:16,659] Trial 2 finished with value: 0.5299999999999999 and parameters: {'kernel': 'rbf', 'C': 0.9229388317394318, 'class_weight': None, 'gamma': 0.0028308141496998056}. Best is trial 0 with value: 0.5640000000000001.
[I 2026-07-28 19:08:16,950] Trial 3 finished with value: 0.5599999999999999 and parameters: {'kernel': 'linear', 'C': 1.8143501127770325, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.5640000000000001.
[I 2026-07-28 19:08:17,215] Trial 4 finished with value: 0.5316666666666666 and parameters: {'kernel': 'rbf', 'C': 0.8162592647338452, 'class_weight': None, 'gamma': 0.002123261760236048}. Best is trial 0 with value: 0.5640000000000001.
[I 2026-07-28 19:08:17,454] Trial 5 finished with value: 0.5143333333333333 and parameters: {'kernel': 'rbf', 'C': 0.6258029168785181, 'class_weight': 'balanced', 'gamma': 0.0002808915139812627}. Best is trial 0 with value: 0.5640000000000001.
[I 2026-07-28 19:08:17,741] Trial 6 finished with value: 0.5683333333333332 and parameters: {'kernel': 'linear', 'C': 0.2237532750003076, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.5683333333333332.
[I 2026-07-28 19:08:18,027] Trial 7 finished with value: 0.5586666666666666 and parameters: {'kernel': 'linear', 'C': 0.6848369919240023, 'class_weight': None}. Best is trial 6 with value: 0.5683333333333332.
[I 2026-07-28 19:08:18,300] Trial 8 finished with value: 0.5736666666666665 and parameters: {'kernel': 'linear', 'C': 4.4156141241212605, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:18,536] Trial 9 finished with value: 0.5143333333333333 and parameters: {'kernel': 'rbf', 'C': 0.5061091517614386, 'class_weight': 'balanced', 'gamma': 0.0002457457272781316}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:18,760] Trial 10 finished with value: 0.5583333333333332 and parameters: {'kernel': 'linear', 'C': 0.07308036295030698, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:19,007] Trial 11 finished with value: 0.5573333333333333 and parameters: {'kernel': 'linear', 'C': 0.14411160549367552, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:19,281] Trial 12 finished with value: 0.5636666666666665 and parameters: {'kernel': 'linear', 'C': 0.2079134345256642, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:19,498] Trial 13 finished with value: 0.5656666666666665 and parameters: {'kernel': 'linear', 'C': 0.23295113619057692, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:19,736] Trial 14 finished with value: 0.5623333333333334 and parameters: {'kernel': 'linear', 'C': 3.828857749639392, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:19,970] Trial 15 finished with value: 0.5579999999999999 and parameters: {'kernel': 'linear', 'C': 0.05030987217730184, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:20,217] Trial 16 finished with value: 0.5619999999999998 and parameters: {'kernel': 'linear', 'C': 0.3025480895383479, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:20,418] Trial 17 finished with value: 0.5586666666666668 and parameters: {'kernel': 'linear', 'C': 1.921121018116134, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:20,634] Trial 18 finished with value: 0.5693333333333332 and parameters: {'kernel': 'linear', 'C': 0.13399598639503651, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:20,846] Trial 19 finished with value: 0.5619999999999999 and parameters: {'kernel': 'linear', 'C': 0.11348530205556787, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:21,067] Trial 20 finished with value: 0.5519999999999999 and parameters: {'kernel': 'linear', 'C': 1.3567258921253544, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:21,320] Trial 21 finished with value: 0.569 and parameters: {'kernel': 'linear', 'C': 0.12226180596609057, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:21,540] Trial 22 finished with value: 0.5723333333333332 and parameters: {'kernel': 'linear', 'C': 0.11338512302448527, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:21,765] Trial 23 finished with value: 0.5636666666666665 and parameters: {'kernel': 'linear', 'C': 0.3506194335050055, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:21,991] Trial 24 finished with value: 0.5643333333333332 and parameters: {'kernel': 'linear', 'C': 0.09273643464334418, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:22,238] Trial 25 finished with value: 0.5526666666666666 and parameters: {'kernel': 'linear', 'C': 0.07010072882840658, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:22,472] Trial 26 finished with value: 0.5063333333333333 and parameters: {'kernel': 'rbf', 'C': 0.16958463117982236, 'class_weight': 'balanced', 'gamma': 0.009846340448794165}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:22,710] Trial 27 finished with value: 0.5623333333333334 and parameters: {'kernel': 'linear', 'C': 4.917229517408837, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:22,928] Trial 28 finished with value: 0.5579999999999999 and parameters: {'kernel': 'linear', 'C': 0.050300802525232606, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:23,166] Trial 29 finished with value: 0.5653333333333332 and parameters: {'kernel': 'linear', 'C': 0.339650838442091, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:23,422] Trial 30 finished with value: 0.5569999999999999 and parameters: {'kernel': 'linear', 'C': 2.044936202960138, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:23,657] Trial 31 finished with value: 0.5676666666666667 and parameters: {'kernel': 'linear', 'C': 0.1280559620550252, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:23,888] Trial 32 finished with value: 0.5643333333333332 and parameters: {'kernel': 'linear', 'C': 0.09170990147079497, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:24,124] Trial 33 finished with value: 0.5649999999999998 and parameters: {'kernel': 'linear', 'C': 0.17489357461528135, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:24,359] Trial 34 finished with value: 0.5126666666666666 and parameters: {'kernel': 'rbf', 'C': 2.670767955610663, 'class_weight': 'balanced', 'gamma': 0.0006567671942926749}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:24,872] Trial 35 finished with value: 0.5556666666666666 and parameters: {'kernel': 'linear', 'C': 1.202955245402216, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:25,151] Trial 36 finished with value: 0.508 and parameters: {'kernel': 'rbf', 'C': 0.10403576307867858, 'class_weight': 'balanced', 'gamma': 0.009503668873125109}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:25,365] Trial 37 finished with value: 0.5616666666666666 and parameters: {'kernel': 'linear', 'C': 0.07434015681476219, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:25,583] Trial 38 finished with value: 0.5556666666666666 and parameters: {'kernel': 'linear', 'C': 0.42094114821000705, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:25,811] Trial 39 finished with value: 0.5126666666666666 and parameters: {'kernel': 'rbf', 'C': 0.2820011160864498, 'class_weight': 'balanced', 'gamma': 0.000890298373504091}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:26,035] Trial 40 finished with value: 0.5619999999999999 and parameters: {'kernel': 'linear', 'C': 0.15948289454630202, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:26,274] Trial 41 finished with value: 0.5706666666666665 and parameters: {'kernel': 'linear', 'C': 0.1178129527885558, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:26,488] Trial 42 finished with value: 0.5693333333333332 and parameters: {'kernel': 'linear', 'C': 0.123913903908827, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:26,727] Trial 43 finished with value: 0.5479999999999999 and parameters: {'kernel': 'linear', 'C': 0.06366374504169531, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:26,966] Trial 44 finished with value: 0.5666666666666665 and parameters: {'kernel': 'linear', 'C': 0.22242799895312462, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:27,200] Trial 45 finished with value: 0.5673333333333334 and parameters: {'kernel': 'linear', 'C': 0.08504126573599356, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:27,445] Trial 46 finished with value: 0.5599999999999999 and parameters: {'kernel': 'linear', 'C': 0.5420576802332312, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:27,696] Trial 47 finished with value: 0.5143333333333333 and parameters: {'kernel': 'rbf', 'C': 0.8772217426775594, 'class_weight': 'balanced', 'gamma': 0.0001018843974760592}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:27,951] Trial 48 finished with value: 0.5726666666666665 and parameters: {'kernel': 'linear', 'C': 0.14541401921911137, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:28,294] Trial 49 finished with value: 0.5553333333333333 and parameters: {'kernel': 'linear', 'C': 0.18323010266531986, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:28,590] Trial 50 finished with value: 0.5686666666666665 and parameters: {'kernel': 'linear', 'C': 0.25920328523698305, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:28,861] Trial 51 finished with value: 0.5726666666666665 and parameters: {'kernel': 'linear', 'C': 0.14193336989416472, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:29,143] Trial 52 finished with value: 0.5726666666666665 and parameters: {'kernel': 'linear', 'C': 0.1462645642268326, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:29,375] Trial 53 finished with value: 0.5716666666666665 and parameters: {'kernel': 'linear', 'C': 0.1581942386379504, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:29,582] Trial 54 finished with value: 0.5633333333333331 and parameters: {'kernel': 'linear', 'C': 0.21065369581265975, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:29,826] Trial 55 finished with value: 0.5726666666666665 and parameters: {'kernel': 'linear', 'C': 0.1442793825193531, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:30,080] Trial 56 finished with value: 0.5573333333333333 and parameters: {'kernel': 'linear', 'C': 0.1419687838049827, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:30,313] Trial 57 finished with value: 0.5726666666666667 and parameters: {'kernel': 'linear', 'C': 0.10322113500061425, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:30,522] Trial 58 finished with value: 0.5633333333333331 and parameters: {'kernel': 'linear', 'C': 0.19414801487727387, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:30,736] Trial 59 finished with value: 0.5533333333333332 and parameters: {'kernel': 'linear', 'C': 0.06168584458762017, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:30,958] Trial 60 finished with value: 0.513 and parameters: {'kernel': 'rbf', 'C': 0.4336317168489955, 'class_weight': 'balanced', 'gamma': 0.003284568054593505}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:31,172] Trial 61 finished with value: 0.5726666666666667 and parameters: {'kernel': 'linear', 'C': 0.10156084421935536, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:31,384] Trial 62 finished with value: 0.5726666666666667 and parameters: {'kernel': 'linear', 'C': 0.10264516731760157, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:31,598] Trial 63 finished with value: 0.5726666666666667 and parameters: {'kernel': 'linear', 'C': 0.10223045058591299, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:31,828] Trial 64 finished with value: 0.5609999999999999 and parameters: {'kernel': 'linear', 'C': 0.0811445759250089, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:32,047] Trial 65 finished with value: 0.5726666666666667 and parameters: {'kernel': 'linear', 'C': 0.10328881075040813, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:32,262] Trial 66 finished with value: 0.5643333333333332 and parameters: {'kernel': 'linear', 'C': 0.09456743577707133, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:32,485] Trial 67 finished with value: 0.5496666666666666 and parameters: {'kernel': 'linear', 'C': 0.05827765510844655, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:32,694] Trial 68 finished with value: 0.5626666666666666 and parameters: {'kernel': 'linear', 'C': 0.10396728948709283, 'class_weight': None}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:32,997] Trial 69 finished with value: 0.5543333333333332 and parameters: {'kernel': 'linear', 'C': 0.07463983736500186, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.5736666666666665.
[I 2026-07-28 19:08:33,220] Trial 70 finished with value: 0.5753333333333333 and parameters: {'kernel': 'linear', 'C': 0.10440890541682227, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:33,501] Trial 71 finished with value: 0.5753333333333333 and parameters: {'kernel': 'linear', 'C': 0.10619021666404231, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:33,718] Trial 72 finished with value: 0.5726666666666667 and parameters: {'kernel': 'linear', 'C': 0.10165617575820379, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:33,963] Trial 73 finished with value: 0.5656666666666667 and parameters: {'kernel': 'linear', 'C': 0.08846703804594548, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:34,210] Trial 74 finished with value: 0.5556666666666666 and parameters: {'kernel': 'linear', 'C': 1.2027363995588738, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:34,423] Trial 75 finished with value: 0.5526666666666666 and parameters: {'kernel': 'linear', 'C': 0.06920601076710915, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:34,644] Trial 76 finished with value: 0.5539999999999999 and parameters: {'kernel': 'linear', 'C': 0.7413560269809217, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:34,857] Trial 77 finished with value: 0.564 and parameters: {'kernel': 'linear', 'C': 0.10745529114683924, 'class_weight': None}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:35,080] Trial 78 finished with value: 0.5143333333333333 and parameters: {'kernel': 'rbf', 'C': 2.834456130883707, 'class_weight': 'balanced', 'gamma': 0.0003972786226873776}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:35,317] Trial 79 finished with value: 0.5593333333333331 and parameters: {'kernel': 'linear', 'C': 0.07951016546694793, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:35,538] Trial 80 finished with value: 0.5516666666666666 and parameters: {'kernel': 'linear', 'C': 0.054700299874735854, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:35,757] Trial 81 finished with value: 0.571 and parameters: {'kernel': 'linear', 'C': 0.09859500130203083, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:35,979] Trial 82 finished with value: 0.5723333333333332 and parameters: {'kernel': 'linear', 'C': 0.116199009441534, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:36,220] Trial 83 finished with value: 0.5676666666666667 and parameters: {'kernel': 'linear', 'C': 0.12679358734207716, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:36,435] Trial 84 finished with value: 0.5493333333333332 and parameters: {'kernel': 'linear', 'C': 0.06769855567696598, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:36,667] Trial 85 finished with value: 0.5656666666666667 and parameters: {'kernel': 'linear', 'C': 0.0882253210633885, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:36,913] Trial 86 finished with value: 0.571 and parameters: {'kernel': 'linear', 'C': 0.1007256597591906, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:37,132] Trial 87 finished with value: 0.5619999999999999 and parameters: {'kernel': 'linear', 'C': 0.1129783558357957, 'class_weight': None}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:37,351] Trial 88 finished with value: 0.5576666666666665 and parameters: {'kernel': 'linear', 'C': 0.0780204437898808, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:37,566] Trial 89 finished with value: 0.524 and parameters: {'kernel': 'rbf', 'C': 4.8430512726440265, 'class_weight': 'balanced', 'gamma': 0.0015965395361550296}. Best is trial 70 with value: 0.5753333333333333.
[I 2026-07-28 19:08:37,794] Trial 90 finished with value: 0.57 and parameters: {'kernel': 'linear', 'C': 0.16347662755009815, 'class_weight': 'balanced'}. Best is trial 70 with value: 0.5753333333333333.

({'kernel': 'linear', 'C': 0.10440890541682227, 'class_weight': 'balanced'},
 0.5753333333333333)

### XGBoost

In [25]:
def objective_xgb(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 2, 3),

        'learning_rate': trial.suggest_float(
            'learning_rate',
            0.02,
            0.05,
            log=True
        ),

        'n_estimators': trial.suggest_int('n_estimators', 80, 180),

        'min_child_weight': trial.suggest_float('min_child_weight', 3.0, 10.0),

        'gamma': trial.suggest_float('gamma', 0.1, 0.3),

        'subsample': trial.suggest_float('subsample', 0.8, 1.0),

        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.8, 1.0),

        'reg_lambda': trial.suggest_float('reg_lambda', 1.0, 10.0, log=True),

        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 0.1),

        'max_delta_step': trial.suggest_int('max_delta_step', 0, 2),

        'random_state': 42,
        'n_jobs': -1,
        'eval_metric': 'logloss'
    }

    model = Pipeline([
        ('clf', XGBClassifier(**params))
    ])

    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=inner_cv,
        scoring='roc_auc')

    mean_score = score.mean()
    std_score = score.std()

    return mean_score - alpha * min(std_score, stability_std_cap)

In [26]:
study_xgb = optuna.create_study(direction='maximize', sampler=sampler)
study_xgb.optimize(objective_xgb, n_trials=100)

study_xgb.best_params, study_xgb.best_value

[I 2026-07-28 19:08:40,104] A new study created in memory with name: no-name-651be8c1-9768-4bd9-b04d-fe7a64908b84
[I 2026-07-28 19:08:41,486] Trial 0 finished with value: 0.4858333333333334 and parameters: {'max_depth': 3, 'learning_rate': 0.025867862988964596, 'n_estimators': 82, 'min_child_weight': 7.518306071350175, 'gamma': 0.13542213588140978, 'subsample': 0.9880917168705828, 'colsample_bytree': 0.9907857154005175, 'reg_lambda': 8.219859422471128, 'reg_alpha': 0.03701587002554444, 'max_delta_step': 0}. Best is trial 0 with value: 0.4858333333333334.
[I 2026-07-28 19:08:43,090] Trial 1 finished with value: 0.4875 and parameters: {'max_depth': 3, 'learning_rate': 0.02960885405829663, 'n_estimators': 177, 'min_child_weight': 9.74533983962477, 'gamma': 0.270601891093472, 'subsample': 0.8588897784139171, 'colsample_bytree': 0.8770195457203851, 'reg_lambda': 7.0980110566411465, 'reg_alpha': 0.031692200515627766, 'max_delta_step': 0}. Best is trial 1 with value: 0.4875.
[I 2026-07-28 19:08:44,752] Trial 2 finished with value: 0.4471666666666666 and parameters: {'max_depth': 3, 'learning_rate': 0.0471588748252506, 'n_estimators': 150, 'min_child_weight': 6.990428190625555, 'gamma': 0.11943529875415371, 'subsample': 0.923001445339834, 'colsample_bytree': 0.9980107700208527, 'reg_lambda': 1.3806513288500464, 'reg_alpha': 0.05183296523637368, 'max_delta_step': 2}. Best is trial 1 with value: 0.4875.
[I 2026-07-28 19:08:47,000] Trial 3 finished with value: 0.5193333333333333 and parameters: {'max_depth': 3, 'learning_rate': 0.03787916925072611, 'n_estimators': 150, 'min_child_weight': 5.516438058538286, 'gamma': 0.15871836885289867, 'subsample': 0.9618722310957027, 'colsample_bytree': 0.9620226789358362, 'reg_lambda': 7.363297006759709, 'reg_alpha': 0.09132405525564713, 'max_delta_step': 1}. Best is trial 3 with value: 0.5193333333333333.
[I 2026-07-28 19:08:49,064] Trial 4 finished with value: 0.43966666666666665 and parameters: {'max_depth': 3, 'learning_rate': 0.041562684077602705, 'n_estimators': 145, 'min_child_weight': 7.913768140803923, 'gamma': 0.2591585338872202, 'subsample': 0.9780010683635133, 'colsample_bytree': 0.8675990313703072, 'reg_lambda': 2.3745589332672776, 'reg_alpha': 0.009398193984086901, 'max_delta_step': 1}. Best is trial 3 with value: 0.5193333333333333.
[I 2026-07-28 19:08:50,844] Trial 5 finished with value: 0.47316666666666657 and parameters: {'max_depth': 2, 'learning_rate': 0.03064150377074502, 'n_estimators': 134, 'min_child_weight': 5.005788764897991, 'gamma': 0.21816665211380215, 'subsample': 0.8061000499878099, 'colsample_bytree': 0.8074696377498429, 'reg_lambda': 6.64661557126371, 'reg_alpha': 0.03601906414112629, 'max_delta_step': 0}. Best is trial 3 with value: 0.5193333333333333.
[I 2026-07-28 19:08:52,284] Trial 6 finished with value: 0.4818333333333334 and parameters: {'max_depth': 3, 'learning_rate': 0.04049871437822416, 'n_estimators': 101, 'min_child_weight': 7.360233330733002, 'gamma': 0.1170694929987536, 'subsample': 0.8103363442337216, 'colsample_bytree': 0.9062709263136296, 'reg_lambda': 3.472442968552307, 'reg_alpha': 0.06374299014982066, 'max_delta_step': 2}. Best is trial 3 with value: 0.5193333333333333.
[I 2026-07-28 19:08:53,619] Trial 7 finished with value: 0.48783333333333334 and parameters: {'max_depth': 3, 'learning_rate': 0.03209863473353107, 'n_estimators': 112, 'min_child_weight': 8.566303363380925, 'gamma': 0.15416645025241485, 'subsample': 0.8877942841411273, 'colsample_bytree': 0.8156912762684533, 'reg_lambda': 1.060109541566103, 'reg_alpha': 0.09626484146779252, 'max_delta_step': 2}. Best is trial 3 with value: 0.5193333333333333.
[I 2026-07-28 19:08:55,023] Trial 8 finished with value: 0.4873333333333334 and parameters: {'max_depth': 3, 'learning_rate': 0.029091675451491463, 'n_estimators': 97, 'min_child_weight': 4.095059298697603, 'gamma': 0.15004857963291907, 'subsample': 0.9098453329412242, 'colsample_bytree': 0.9429191845400124, 'reg_lambda': 4.572959727541133, 'reg_alpha': 0.027993389694594285, 'max_delta_step': 2}. Best is trial 3 with value: 0.5193333333333333.
[I 2026-07-28 19:08:56,923] Trial 9 finished with value: 0.48433333333333334 and parameters: {'max_depth': 3, 'learning_rate': 0.033237599628821946, 'n_estimators': 141, 'min_child_weight': 5.937200436994529, 'gamma': 0.1495461979002315, 'subsample': 0.8711945357302524, 'colsample_bytree': 0.9515692220928739, 'reg_lambda': 1.0336975540234519, 'reg_alpha': 0.011607264050691624, 'max_delta_step': 0}. Best is trial 3 with value: 0.5193333333333333.
[I 2026-07-28 19:08:59,300] Trial 10 finished with value: 0.48816666666666675 and parameters: {'max_depth': 2, 'learning_rate': 0.02303215355865767, 'n_estimators': 170, 'min_child_weight': 3.5461836025740983, 'gamma': 0.1979973341281275, 'subsample': 0.9500009180898407, 'colsample_bytree': 0.9481694986349387, 'reg_lambda': 9.840239452885486, 'reg_alpha': 0.09617364301443236, 'max_delta_step': 1}. Best is trial 3 with value: 0.5193333333333333.
[I 2026-07-28 19:09:01,658] Trial 11 finished with value: 0.488 and parameters: {'max_depth': 2, 'learning_rate': 0.02064281311325517, 'n_estimators': 173, 'min_child_weight': 3.086145569200114, 'gamma': 0.20480585235841772, 'subsample': 0.9525552620374604, 'colsample_bytree': 0.9500063537259182, 'reg_lambda': 9.880805128089667, 'reg_alpha': 0.0966820937375966, 'max_delta_step': 1}. Best is trial 3 with value: 0.5193333333333333.
[I 2026-07-28 19:09:04,025] Trial 12 finished with value: 0.5139999999999999 and parameters: {'max_depth': 2, 'learning_rate': 0.02185972128139361, 'n_estimators': 161, 'min_child_weight': 5.576994364888572, 'gamma': 0.18703693591465143, 'subsample': 0.9487044450144064, 'colsample_bytree': 0.9160057714522106, 'reg_lambda': 5.154273139979344, 'reg_alpha': 0.07751045776277785, 'max_delta_step': 1}. Best is trial 3 with value: 0.5193333333333333.
[I 2026-07-28 19:09:05,708] Trial 13 finished with value: 0.5148333333333334 and parameters: {'max_depth': 2, 'learning_rate': 0.03700277618012178, 'n_estimators': 159, 'min_child_weight': 5.777531161262918, 'gamma': 0.17377304264714843, 'subsample': 0.9487522155457897, 'colsample_bytree': 0.9130957510170812, 'reg_lambda': 5.164826990582233, 'reg_alpha': 0.07117161142696696, 'max_delta_step': 1}. Best is trial 3 with value: 0.5193333333333333.
[I 2026-07-28 19:09:07,364] Trial 14 finished with value: 0.523 and parameters: {'max_depth': 2, 'learning_rate': 0.036683126062564464, 'n_estimators': 123, 'min_child_weight': 4.824621418010269, 'gamma': 0.17927316660209525, 'subsample': 0.9989471065094118, 'colsample_bytree': 0.8608822018500459, 'reg_lambda': 2.954650909393946, 'reg_alpha': 0.07888992964543697, 'max_delta_step': 1}. Best is trial 14 with value: 0.523.
[I 2026-07-28 19:09:09,232] Trial 15 finished with value: 0.5211666666666668 and parameters: {'max_depth': 2, 'learning_rate': 0.03658600470600312, 'n_estimators': 120, 'min_child_weight': 4.786295567588813, 'gamma': 0.22912492610230645, 'subsample': 0.9929678557556023, 'colsample_bytree': 0.8440912208928119, 'reg_lambda': 2.3117306609019375, 'reg_alpha': 0.0824705869570815, 'max_delta_step': 1}. Best is trial 14 with value: 0.523.
[I 2026-07-28 19:09:10,754] Trial 16 finished with value: 0.5178333333333333 and parameters: {'max_depth': 2, 'learning_rate': 0.04904929630796581, 'n_estimators': 120, 'min_child_weight': 4.527885799143811, 'gamma': 0.24174176548133652, 'subsample': 0.999497969466314, 'colsample_bytree': 0.8425475930556395, 'reg_lambda': 2.1131769344036493, 'reg_alpha': 0.0804376325178205, 'max_delta_step': 1}. Best is trial 14 with value: 0.523.
[I 2026-07-28 19:09:12,269] Trial 17 finished with value: 0.514 and parameters: {'max_depth': 2, 'learning_rate': 0.042848854530189794, 'n_estimators': 123, 'min_child_weight': 4.487326160626671, 'gamma': 0.29060900652987953, 'subsample': 0.9757148218742308, 'colsample_bytree': 0.8493488935198059, 'reg_lambda': 2.2610414688525706, 'reg_alpha': 0.05811601903267766, 'max_delta_step': 1}. Best is trial 14 with value: 0.523.
[I 2026-07-28 19:09:13,711] Trial 18 finished with value: 0.4745 and parameters: {'max_depth': 2, 'learning_rate': 0.03541973599115535, 'n_estimators': 108, 'min_child_weight': 6.366500928840277, 'gamma': 0.22723640325132527, 'subsample': 0.9268763116216212, 'colsample_bytree': 0.8323070027792746, 'reg_lambda': 3.138518658537339, 'reg_alpha': 0.08297840231378385, 'max_delta_step': 2}. Best is trial 14 with value: 0.523.
[I 2026-07-28 19:09:15,379] Trial 19 finished with value: 0.4933333333333334 and parameters: {'max_depth': 2, 'learning_rate': 0.04511905880600412, 'n_estimators': 128, 'min_child_weight': 3.8516177419576434, 'gamma': 0.23779667064522092, 'subsample': 0.9991396281754713, 'colsample_bytree': 0.8789343802898418, 'reg_lambda': 1.7718098795066004, 'reg_alpha': 0.06684180768523765, 'max_delta_step': 0}. Best is trial 14 with value: 0.523.
[I 2026-07-28 19:09:16,820] Trial 20 finished with value: 0.476 and parameters: {'max_depth': 2, 'learning_rate': 0.026430323214386424, 'n_estimators': 89, 'min_child_weight': 4.9155257094998035, 'gamma': 0.17784396133428126, 'subsample': 0.8464021363356227, 'colsample_bytree': 0.8581620203245389, 'reg_lambda': 2.992315557597116, 'reg_alpha': 0.08441736497507055, 'max_delta_step': 1}. Best is trial 14 with value: 0.523.
[I 2026-07-28 19:09:18,521] Trial 21 finished with value: 0.517 and parameters: {'max_depth': 2, 'learning_rate': 0.0377024930449055, 'n_estimators': 136, 'min_child_weight': 5.650333945915033, 'gamma': 0.167867505791909, 'subsample': 0.9675255549831632, 'colsample_bytree': 0.8874568334785875, 'reg_lambda': 3.9282323090824067, 'reg_alpha': 0.08781698665418719, 'max_delta_step': 1}. Best is trial 14 with value: 0.523.
[I 2026-07-28 19:09:20,134] Trial 22 finished with value: 0.5243333333333333 and parameters: {'max_depth': 2, 'learning_rate': 0.03542714492053764, 'n_estimators': 116, 'min_child_weight': 5.102671434357457, 'gamma': 0.20363138013578888, 'subsample': 0.9675875912379868, 'colsample_bytree': 0.8304962550425217, 'reg_lambda': 2.8428573282036944, 'reg_alpha': 0.07429597332231566, 'max_delta_step': 1}. Best is trial 22 with value: 0.5243333333333333.
[I 2026-07-28 19:09:21,641] Trial 23 finished with value: 0.5138333333333334 and parameters: {'max_depth': 2, 'learning_rate': 0.03488650334026077, 'n_estimators': 114, 'min_child_weight': 4.869492727652455, 'gamma': 0.20765740581039596, 'subsample': 0.9852496998784249, 'colsample_bytree': 0.8268056895875937, 'reg_lambda': 2.69443224129778, 'reg_alpha': 0.07381584477709502, 'max_delta_step': 1}. Best is trial 22 with value: 0.5243333333333333.
[I 2026-07-28 19:09:23,016] Trial 24 finished with value: 0.46499999999999997 and parameters: {'max_depth': 2, 'learning_rate': 0.040044779885504284, 'n_estimators': 123, 'min_child_weight': 6.496374017530027, 'gamma': 0.1899330384001549, 'subsample': 0.9307725271249975, 'colsample_bytree': 0.8009917840298456, 'reg_lambda': 1.7633057803409835, 'reg_alpha': 0.05618481838136301, 'max_delta_step': 1}. Best is trial 22 with value: 0.5243333333333333.
[I 2026-07-28 19:09:24,294] Trial 25 finished with value: 0.4943333333333333 and parameters: {'max_depth': 2, 'learning_rate': 0.03373072573584766, 'n_estimators': 102, 'min_child_weight': 4.323532481227788, 'gamma': 0.25105227958026505, 'subsample': 0.9998999541220575, 'colsample_bytree': 0.8350196921488865, 'reg_lambda': 1.7962435280520224, 'reg_alpha': 0.04330326427766697, 'max_delta_step': 1}. Best is trial 22 with value: 0.5243333333333333.
[I 2026-07-28 19:09:25,905] Trial 26 finished with value: 0.4855 and parameters: {'max_depth': 2, 'learning_rate': 0.026663717603755292, 'n_estimators': 116, 'min_child_weight': 3.423342364771651, 'gamma': 0.10020691798952557, 'subsample': 0.9672315074549979, 'colsample_bytree': 0.8571979449271433, 'reg_lambda': 3.852572784266741, 'reg_alpha': 0.06399114097033995, 'max_delta_step': 0}. Best is trial 22 with value: 0.5243333333333333.
[I 2026-07-28 19:09:27,790] Trial 27 finished with value: 0.5431666666666667 and parameters: {'max_depth': 2, 'learning_rate': 0.043952395396792694, 'n_estimators': 129, 'min_child_weight': 5.2417764655390355, 'gamma': 0.21778519296747625, 'subsample': 0.9846140117288057, 'colsample_bytree': 0.8196455634547446, 'reg_lambda': 2.5003586572468133, 'reg_alpha': 0.07420220539594072, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:29,287] Trial 28 finished with value: 0.48000000000000004 and parameters: {'max_depth': 2, 'learning_rate': 0.04660571445075505, 'n_estimators': 128, 'min_child_weight': 6.1781162253473845, 'gamma': 0.20923649695081104, 'subsample': 0.9406023257959292, 'colsample_bytree': 0.8208597002214452, 'reg_lambda': 2.774708947107816, 'reg_alpha': 0.07186808300279751, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:30,462] Trial 29 finished with value: 0.5221666666666667 and parameters: {'max_depth': 2, 'learning_rate': 0.04349654554002118, 'n_estimators': 81, 'min_child_weight': 5.344856801521497, 'gamma': 0.18612142707674167, 'subsample': 0.9798632209280156, 'colsample_bytree': 0.8935329186269679, 'reg_lambda': 1.450251642779849, 'reg_alpha': 0.04735758830168268, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:31,845] Trial 30 finished with value: 0.4646666666666667 and parameters: {'max_depth': 2, 'learning_rate': 0.039333558051886874, 'n_estimators': 109, 'min_child_weight': 7.146872101236191, 'gamma': 0.21805127364718968, 'subsample': 0.906176188147524, 'colsample_bytree': 0.8168768240339972, 'reg_lambda': 3.6008123317461105, 'reg_alpha': 0.05934603409754338, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:33,198] Trial 31 finished with value: 0.5321666666666667 and parameters: {'max_depth': 2, 'learning_rate': 0.04368136120066185, 'n_estimators': 87, 'min_child_weight': 5.32918718160696, 'gamma': 0.19027945160069207, 'subsample': 0.9836496592220219, 'colsample_bytree': 0.8860982177971299, 'reg_lambda': 1.2190090988185451, 'reg_alpha': 0.04477449938070997, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:34,492] Trial 32 finished with value: 0.5205 and parameters: {'max_depth': 2, 'learning_rate': 0.044154112144358805, 'n_estimators': 87, 'min_child_weight': 5.012157652586362, 'gamma': 0.19741212611047348, 'subsample': 0.9846240293998411, 'colsample_bytree': 0.8685455518612537, 'reg_lambda': 1.2400264400750474, 'reg_alpha': 0.02513580550282425, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:36,234] Trial 33 finished with value: 0.45433333333333326 and parameters: {'max_depth': 2, 'learning_rate': 0.04679689042472975, 'n_estimators': 132, 'min_child_weight': 6.748275913236311, 'gamma': 0.16962882183154232, 'subsample': 0.9640511184072965, 'colsample_bytree': 0.9306399977065447, 'reg_lambda': 1.992529652993785, 'reg_alpha': 0.04463910617624979, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:37,966] Trial 34 finished with value: 0.5183333333333332 and parameters: {'max_depth': 2, 'learning_rate': 0.03909076628544826, 'n_estimators': 95, 'min_child_weight': 5.407636789440177, 'gamma': 0.13288790314989363, 'subsample': 0.9741458875919532, 'colsample_bytree': 0.978628066384343, 'reg_lambda': 1.4551294750366193, 'reg_alpha': 0.05193980265863801, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:39,787] Trial 35 finished with value: 0.4881666666666667 and parameters: {'max_depth': 2, 'learning_rate': 0.04883618967503175, 'n_estimators': 139, 'min_child_weight': 3.92267045273767, 'gamma': 0.21775558335805156, 'subsample': 0.96058607157109, 'colsample_bytree': 0.8757670240995636, 'reg_lambda': 2.591333948335988, 'reg_alpha': 0.018102873122163854, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:41,446] Trial 36 finished with value: 0.48183333333333334 and parameters: {'max_depth': 2, 'learning_rate': 0.04158323233462602, 'n_estimators': 148, 'min_child_weight': 9.11571842249291, 'gamma': 0.2744089567979087, 'subsample': 0.9878054471339751, 'colsample_bytree': 0.8593083560346714, 'reg_lambda': 4.482160262462262, 'reg_alpha': 0.08889492219119681, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:42,903] Trial 37 finished with value: 0.5106666666666666 and parameters: {'max_depth': 2, 'learning_rate': 0.028731201038789657, 'n_estimators': 106, 'min_child_weight': 5.195476217261085, 'gamma': 0.17893524551870427, 'subsample': 0.9358688089813336, 'colsample_bytree': 0.8834883334836635, 'reg_lambda': 1.2477800459294484, 'reg_alpha': 0.03674548483386242, 'max_delta_step': 0}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:44,536] Trial 38 finished with value: 0.5219999999999999 and parameters: {'max_depth': 2, 'learning_rate': 0.0312014247559839, 'n_estimators': 155, 'min_child_weight': 6.190213561953127, 'gamma': 0.13704942149316757, 'subsample': 0.9875650387969208, 'colsample_bytree': 0.8382356024520468, 'reg_lambda': 3.3777761419358634, 'reg_alpha': 0.07688353825824111, 'max_delta_step': 1}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:45,686] Trial 39 finished with value: 0.4755 and parameters: {'max_depth': 3, 'learning_rate': 0.04177798196090356, 'n_estimators': 91, 'min_child_weight': 8.112601950642231, 'gamma': 0.1630000744653334, 'subsample': 0.974174266569035, 'colsample_bytree': 0.9003693852053096, 'reg_lambda': 6.321551073863594, 'reg_alpha': 0.06762590016894428, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:47,312] Trial 40 finished with value: 0.48899999999999993 and parameters: {'max_depth': 2, 'learning_rate': 0.03555096821039787, 'n_estimators': 142, 'min_child_weight': 5.97190480974689, 'gamma': 0.19519458434828915, 'subsample': 0.9182816604198695, 'colsample_bytree': 0.812051333989122, 'reg_lambda': 2.466897390875867, 'reg_alpha': 0.050820859195297816, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:48,548] Trial 41 finished with value: 0.5226666666666667 and parameters: {'max_depth': 2, 'learning_rate': 0.04447510462483499, 'n_estimators': 81, 'min_child_weight': 5.34782653611956, 'gamma': 0.184645401371501, 'subsample': 0.9828084312268199, 'colsample_bytree': 0.8874489966008007, 'reg_lambda': 1.4973311813594292, 'reg_alpha': 0.047582842399829094, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:49,778] Trial 42 finished with value: 0.5105 and parameters: {'max_depth': 2, 'learning_rate': 0.045206215691695854, 'n_estimators': 84, 'min_child_weight': 4.4542274768127745, 'gamma': 0.18345183439339377, 'subsample': 0.8910333148467526, 'colsample_bytree': 0.8522909110438773, 'reg_lambda': 1.271535348786434, 'reg_alpha': 0.03882737807568393, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.
[I 2026-07-28 19:09:50,904] Trial 43 finished with value: 0.4993333333333333 and parameters: {'max_depth': 2, 'learning_rate': 0.0496513393484082, 'n_estimators': 80, 'min_child_weight': 5.328115353596328, 'gamma': 0.21048126337184392, 'subsample': 0.8241375725107211, 'colsample_bytree': 0.8730370670909793, 'reg_lambda': 1.1011646752380901, 'reg_alpha': 0.041528143763886936, 'max_delta_step': 2}. Best is trial 27 with value: 0.5431666666666667.

({'max_depth': 2,
  'learning_rate': 0.04772753454707194,
  'n_estimators': 135,
  'min_child_weight': 5.708054401119242,
  'gamma': 0.29256771005742016,
  'subsample': 0.9879709827503215,
  'colsample_bytree': 0.9936378122095748,
  'reg_lambda': 1.4992089279125758,
  'reg_alpha': 0.07944657116549703,
  'max_delta_step': 2},
 0.5536666666666666)

## Validation Set Metrics

In [27]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

In [28]:
models = {
    'Logistic Regression': Pipeline([
        ('scaler', StandardScaler()),
        ('clf', LogisticRegression(**study_lr.best_params))
    ]),
    'Random Forest': Pipeline([
        ('clf', RandomForestClassifier(**study_rf.best_params))
    ]),
    'Linear Discriminant Analysis': Pipeline([
        ('scaler', StandardScaler()),
        ('clf', LinearDiscriminantAnalysis(**study_lda.best_params))
    ]),
    'Support Vector Machine': Pipeline([
        ('scaler', StandardScaler()),
        ('clf', SVC(**study_svc.best_params))
    ]),
    'XGBoost': Pipeline([
        ('clf', XGBClassifier(**study_xgb.best_params))
    ])
}

In [29]:
val_predictions = {}
val_metrics = {}
val_reports ={}

for model_name, model in models.items():

    model.fit(X_train, y_train)

    val_predictions[model_name] = model.predict(X_val)

    val_metrics[model_name] = {
        'Accuracy': accuracy_score(y_val, val_predictions[model_name]),
        'Precision': precision_score(y_val, val_predictions[model_name], average='weighted', zero_division=0),
        'Recall': recall_score(y_val, val_predictions[model_name], average='weighted', zero_division=0),
        'F1': f1_score(y_val, val_predictions[model_name], average='weighted', zero_division=0),
    }

    val_reports[model_name] = classification_report(y_val, val_predictions[model_name], zero_division=0)

### Summary Metrics

In [30]:
df_val_metrics = pd.DataFrame(val_metrics)
df_val_metrics.T.sort_values(by='Accuracy', ascending=False)

                              Accuracy  Precision    Recall        F1
Random Forest                 0.789474   0.854251  0.789474  0.782297
XGBoost                       0.736842   0.759109  0.736842  0.727689
Support Vector Machine        0.578947   0.587321  0.578947  0.576608
Linear Discriminant Analysis  0.473684   0.473684  0.473684  0.473684
Logistic Regression           0.421053   0.423392  0.421053  0.421053

### Classification Report

In [31]:
for model_names, reports in val_reports.items():
    print(f'{model_names}:\n {reports} \n -------------------------------------------------------')

Logistic Regression:
               precision    recall  f1-score   support

           0       0.44      0.40      0.42        10
           1       0.40      0.44      0.42         9

    accuracy                           0.42        19
   macro avg       0.42      0.42      0.42        19
weighted avg       0.42      0.42      0.42        19

 -------------------------------------------------------
Random Forest:
               precision    recall  f1-score   support

           0       1.00      0.60      0.75        10
           1       0.69      1.00      0.82         9

    accuracy                           0.79        19
   macro avg       0.85      0.80      0.78        19
weighted avg       0.85      0.79      0.78        19

 -------------------------------------------------------
Linear Discriminant Analysis:
               precision    recall  f1-score   support

           0       0.50      0.50      0.50        10
           1       0.44      0.44      0.44         9

    accuracy                           0.47        19
   macro avg       0.47      0.47      0.47        19
weighted avg       0.47      0.47      0.47        19

 -------------------------------------------------------
Support Vector Machine:
               precision    recall  f1-score   support

           0       0.62      0.50      0.56        10
           1       0.55      0.67      0.60         9

    accuracy                           0.58        19
   macro avg       0.59      0.58      0.58        19
weighted avg       0.59      0.58      0.58        19

 -------------------------------------------------------
XGBoost:
               precision    recall  f1-score   support

           0       0.69      0.90      0.78        10
           1       0.83      0.56      0.67         9

    accuracy                           0.74        19
   macro avg       0.76      0.73      0.72        19
weighted avg       0.76      0.74      0.73        19

 -------------------------------------------------------

## Test Set Metrics

In [32]:
X_combined = np.concatenate([X_train, X_val], axis=0)
y_combined = np.concatenate([y_train, y_val], axis=0)

In [33]:
final_model = XGBClassifier(**study_xgb.best_params)
final_model.fit(X_combined, y_combined)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.9936378122095748, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, feature_weights=None,
              gamma=0.29256771005742016, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.04772753454707194,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=2, max_depth=2, max_leaves=None,
              min_child_weight=5.708054401119242, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=135,
              n_jobs=None, num_parallel_tree=None, ...)

### Summary Metrics

In [34]:
test_predictions = final_model.predict(X_test)

test_metrics = {
    'Model': 'XGBoost',
    'Accuracy': accuracy_score(y_test, test_predictions),
    'Precision': precision_score(y_test, test_predictions, average='weighted', zero_division=0),
    'Recall': recall_score(y_test, test_predictions, average='weighted', zero_division=0),
    'F1': f1_score(y_test, test_predictions, average='weighted', zero_division=0),
}

In [35]:
df_test_metrics = pd.DataFrame([test_metrics])
df_test_metrics

     Model  Accuracy  Precision  Recall        F1
0  XGBoost      0.85   0.884615    0.85  0.846547

### Classification Report

In [36]:
print(classification_report(y_test, test_predictions))

              precision    recall  f1-score   support

           0       0.77      1.00      0.87        10
           1       1.00      0.70      0.82        10

    accuracy                           0.85        20
   macro avg       0.88      0.85      0.85        20
weighted avg       0.88      0.85      0.85        20