# NIR White Lagkitan Corn (Three-Class)

In [1]:
import pandas as pd
import numpy as np

## Load Data

In [2]:
df_raw_data = pd.read_csv('appendix_raw_dataset1.csv')
df_raw_data

,Class,730nm,760nm,810nm,860nm,900nm,940nm,Sample No.,Brix (%)
0,Average,235.264008,165.100433,368.587189,2455.738037,107.280037,45.421616,1,5.8
1,Average,221.472671,156.633743,346.383148,2311.896973,126.659653,49.371319,2,4.2
2,Average,245.810333,171.873779,347.271301,2354.817383,109.356422,41.471909,3,3.6
3,Bland,257.167908,177.800476,379.245117,2474.298340,116.277718,41.471909,4,3.0
4,Bland,219.850159,151.553726,332.172546,2170.375977,112.817070,44.434189,5,2.6
...,...,...,...,...,...,...,...,...,...
195,Sweet,279.883057,194.733841,393.455719,2310.737061,137.733719,57.270733,196,9.4
196,Average,268.525482,177.800476,377.468811,2264.336670,119.738358,46.409042,197,8.0
197,Average,270.959228,188.807159,381.021454,2520.698486,117.661972,46.409042,198,7.0
198,Average,272.581757,188.807159,394.343872,2528.818604,116.277718,48.383892,199,6.2
199,Average,228.773972,157.480408,353.488434,2407.017822,107.280037,48.383892,200,6.8

## Preprocessing

### SNV

In [3]:
feature_cols = ['730nm', '760nm', '810nm', '860nm', '900nm', '940nm']

In [4]:
df_snv = df_raw_data.copy()

def snv_row(x):
    x = x.astype(float)
    mean = x.mean()
    std = x.std(ddof=1)

    if std < 1e-8:
        return x * np.nan

    return (x - mean) / std

df_snv[feature_cols] = df_snv[feature_cols].apply(
    snv_row, axis=1, result_type='expand'
)

df_snv = df_snv.dropna()

## Data Preparation

### Selecting Features (X) and Targets (y)

In [7]:
X = df_snv[feature_cols]
y = df_snv['Class'].map({'Bland': 0, 'Average': 1, 'Sweet': 2})

### Data Split

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42)

## Optuna Hyperparameter Tuning

In [11]:
import optuna
from sklearn.model_selection import cross_val_score, RepeatedStratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
from xgboost import XGBClassifier

# For reproducibility
sampler = optuna.samplers.TPESampler(seed=42)
inner_cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=42)

# Tune to penalize instability
alpha = 0.5
stability_std_cap = 0.02

C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Logistic Regression

In [12]:
def objective_lr(trial):
    params = {
        'C': trial.suggest_float('C', 0.03, 3.0, log=True),

        'solver': 'lbfgs',

        'penalty': 'l2',

        'class_weight': trial.suggest_categorical(
            'class_weight',
            [None, 'balanced']
        ),

        'tol': trial.suggest_float('tol', 1e-5, 1e-4, log=True),
        'max_iter': 5000,
        'random_state': 42
    }

    model = Pipeline([
        ('scaler', StandardScaler()),
        ('clf', LogisticRegression(**params))
    ])

    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=inner_cv,
        scoring='f1_macro'
    )

    mean_score = score.mean()
    std_score = score.std()

    return mean_score - alpha * min(std_score, stability_std_cap)

In [13]:
study_lr = optuna.create_study(direction='maximize', sampler=sampler)
study_lr.optimize(objective_lr, n_trials=100)

study_lr.best_params, study_lr.best_value

[I 2026-07-28 18:19:38,838] A new study created in memory with name: no-name-edda9936-537f-4609-97f7-0958761003e0
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
[I 2026-07-28 18:19:39,015] Trial 0 finished with value: 0.2526450544105358 and parameters: {'C': 0.1683454924600351, 'class_weight': None, 'tol': 3.968793330444374e-05}. Best is trial 0 with value: 0.2526450544105358.
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
[I 2026-07-28 18:19:39,177] Trial 1 finished with value: 0.25505360023195073 and parameters: {'C': 0.06154014789262349, 'class_weight': None, 'tol': 7.348118405270451e-05}. Best is trial 1 with value: 0.25505360023195073.
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Lorine Jane\PycharmProjects\Thesis 2nd Final Testing\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

({'C': 1.184853530094305,
  'class_weight': 'balanced',
  'tol': 1.3853621181268501e-05},
 0.344730214138147)

### Random Forest

In [14]:
def objective_rf(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 150, 300),
        'max_depth': trial.suggest_int('max_depth', 2, 6),
        'max_features': trial.suggest_categorical(
            'max_features',
            ['sqrt', 0.5, 0.8]
        ),
        'min_samples_split': trial.suggest_int('min_samples_split', 4, 12),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 6),
        'max_leaf_nodes': trial.suggest_int('max_leaf_nodes', 10, 40),
        'class_weight': trial.suggest_categorical(
            'class_weight',
            [None, 'balanced']
        ),

        'bootstrap': True,
        'n_jobs': -1,
        'random_state': 42
    }

    model = Pipeline([
        ('clf', RandomForestClassifier(**params))
    ])

    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=inner_cv,
        scoring='f1_macro'
    )

    mean_score = score.mean()
    std_score = score.std()

    return mean_score - alpha * std_score

In [15]:
study_rf = optuna.create_study(direction='maximize', sampler=sampler)
study_rf.optimize(objective_rf, n_trials=100)

study_rf.best_params, study_rf.best_value

[I 2026-07-28 18:20:51,402] A new study created in memory with name: no-name-da811dcb-2d4a-407e-b53e-8e078ce52675
[I 2026-07-28 18:20:56,325] Trial 0 finished with value: 0.2789403536421199 and parameters: {'n_estimators': 168, 'max_depth': 4, 'max_features': 0.5, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_leaf_nodes': 26, 'class_weight': None}. Best is trial 0 with value: 0.2789403536421199.
[I 2026-07-28 18:21:04,838] Trial 1 finished with value: 0.3181128323467088 and parameters: {'n_estimators': 296, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_leaf_nodes': 16, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.3181128323467088.
[I 2026-07-28 18:21:10,245] Trial 2 finished with value: 0.28384005232454107 and parameters: {'n_estimators': 208, 'max_depth': 3, 'max_features': 'sqrt', 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_leaf_nodes': 34, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.3181128323467088.
[I 2026-07-28 18:21:16,858] Trial 3 finished with value: 0.2571011056718614 and parameters: {'n_estimators': 266, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_leaf_nodes': 12, 'class_weight': None}. Best is trial 1 with value: 0.3181128323467088.
[I 2026-07-28 18:21:23,102] Trial 4 finished with value: 0.26764828920260375 and parameters: {'n_estimators': 280, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_leaf_nodes': 29, 'class_weight': None}. Best is trial 1 with value: 0.3181128323467088.
[I 2026-07-28 18:21:26,947] Trial 5 finished with value: 0.3057305884049292 and parameters: {'n_estimators': 168, 'max_depth': 5, 'max_features': 0.8, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_leaf_nodes': 23, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.3181128323467088.
[I 2026-07-28 18:21:30,599] Trial 6 finished with value: 0.28187550261329214 and parameters: {'n_estimators': 154, 'max_depth': 5, 'max_features': 0.8, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_leaf_nodes': 33, 'class_weight': None}. Best is trial 1 with value: 0.3181128323467088.
[I 2026-07-28 18:21:35,082] Trial 7 finished with value: 0.25726456771219686 and parameters: {'n_estimators': 193, 'max_depth': 2, 'max_features': 'sqrt', 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_leaf_nodes': 15, 'class_weight': None}. Best is trial 1 with value: 0.3181128323467088.
[I 2026-07-28 18:21:44,841] Trial 8 finished with value: 0.29787621833460265 and parameters: {'n_estimators': 271, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_leaf_nodes': 36, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.3181128323467088.
[I 2026-07-28 18:21:51,448] Trial 9 finished with value: 0.2812716109535062 and parameters: {'n_estimators': 213, 'max_depth': 3, 'max_features': 0.8, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_leaf_nodes': 31, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.3181128323467088.
[I 2026-07-28 18:22:00,229] Trial 10 finished with value: 0.3184021893080331 and parameters: {'n_estimators': 299, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_leaf_nodes': 18, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.3184021893080331.
[I 2026-07-28 18:22:09,618] Trial 11 finished with value: 0.3184021893080331 and parameters: {'n_estimators': 299, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_leaf_nodes': 19, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.3184021893080331.
[I 2026-07-28 18:22:15,298] Trial 12 finished with value: 0.3067410637017354 and parameters: {'n_estimators': 251, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_leaf_nodes': 20, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.3184021893080331.
[I 2026-07-28 18:22:24,085] Trial 13 finished with value: 0.31585289647641734 and parameters: {'n_estimators': 300, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_leaf_nodes': 20, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.3184021893080331.
[I 2026-07-28 18:22:31,548] Trial 14 finished with value: 0.3169087736043177 and parameters: {'n_estimators': 242, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_leaf_nodes': 40, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.3184021893080331.
[I 2026-07-28 18:22:39,185] Trial 15 finished with value: 0.3184573120356162 and parameters: {'n_estimators': 244, 'max_depth': 4, 'max_features': 0.5, 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_leaf_nodes': 11, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:22:46,333] Trial 16 finished with value: 0.30944834167759644 and parameters: {'n_estimators': 236, 'max_depth': 4, 'max_features': 0.5, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_leaf_nodes': 10, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:22:52,990] Trial 17 finished with value: 0.29927192978964046 and parameters: {'n_estimators': 257, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_leaf_nodes': 14, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:23:00,029] Trial 18 finished with value: 0.3005219829809391 and parameters: {'n_estimators': 228, 'max_depth': 4, 'max_features': 0.5, 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_leaf_nodes': 10, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:23:07,554] Trial 19 finished with value: 0.2945026296277527 and parameters: {'n_estimators': 282, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_leaf_nodes': 17, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:23:13,359] Trial 20 finished with value: 0.3072911418862941 and parameters: {'n_estimators': 189, 'max_depth': 5, 'max_features': 0.5, 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_leaf_nodes': 23, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:23:25,171] Trial 21 finished with value: 0.3162710792336719 and parameters: {'n_estimators': 289, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_leaf_nodes': 18, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:23:33,196] Trial 22 finished with value: 0.30882887805872294 and parameters: {'n_estimators': 274, 'max_depth': 4, 'max_features': 'sqrt', 'min_samples_split': 11, 'min_samples_leaf': 2, 'max_leaf_nodes': 20, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:23:39,311] Trial 23 finished with value: 0.3072132276991429 and parameters: {'n_estimators': 258, 'max_depth': 6, 'max_features': 0.8, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_leaf_nodes': 13, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:23:48,704] Trial 24 finished with value: 0.3013318364673544 and parameters: {'n_estimators': 292, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_leaf_nodes': 26, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:23:59,690] Trial 25 finished with value: 0.3122562207705458 and parameters: {'n_estimators': 282, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_leaf_nodes': 23, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:24:06,039] Trial 26 finished with value: 0.27811560886593933 and parameters: {'n_estimators': 245, 'max_depth': 4, 'max_features': 'sqrt', 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_leaf_nodes': 19, 'class_weight': None}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:24:14,972] Trial 27 finished with value: 0.3067265162670796 and parameters: {'n_estimators': 264, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 6, 'max_leaf_nodes': 13, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:24:21,312] Trial 28 finished with value: 0.31414914998697213 and parameters: {'n_estimators': 215, 'max_depth': 6, 'max_features': 0.8, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_leaf_nodes': 22, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:24:27,281] Trial 29 finished with value: 0.27105080009748617 and parameters: {'n_estimators': 230, 'max_depth': 2, 'max_features': 0.5, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_leaf_nodes': 16, 'class_weight': None}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:24:36,240] Trial 30 finished with value: 0.31712265014796126 and parameters: {'n_estimators': 288, 'max_depth': 5, 'max_features': 0.5, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_leaf_nodes': 26, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:24:45,839] Trial 31 finished with value: 0.3001408703008241 and parameters: {'n_estimators': 298, 'max_depth': 4, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_leaf_nodes': 16, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:24:54,570] Trial 32 finished with value: 0.3163321447207798 and parameters: {'n_estimators': 298, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_leaf_nodes': 11, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:25:02,123] Trial 33 finished with value: 0.3069713040385267 and parameters: {'n_estimators': 276, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 11, 'min_samples_leaf': 2, 'max_leaf_nodes': 15, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:25:09,283] Trial 34 finished with value: 0.31564556571491237 and parameters: {'n_estimators': 286, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_leaf_nodes': 12, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:25:16,011] Trial 35 finished with value: 0.27442868360692124 and parameters: {'n_estimators': 269, 'max_depth': 4, 'max_features': 'sqrt', 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_leaf_nodes': 18, 'class_weight': None}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:25:21,087] Trial 36 finished with value: 0.3107617448207143 and parameters: {'n_estimators': 200, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 11, 'min_samples_leaf': 2, 'max_leaf_nodes': 28, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:25:25,895] Trial 37 finished with value: 0.28179736465009453 and parameters: {'n_estimators': 181, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_leaf_nodes': 14, 'class_weight': None}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:25:32,729] Trial 38 finished with value: 0.30377192505944206 and parameters: {'n_estimators': 263, 'max_depth': 5, 'max_features': 0.8, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_leaf_nodes': 22, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:25:40,833] Trial 39 finished with value: 0.31716939852250664 and parameters: {'n_estimators': 293, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_leaf_nodes': 17, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:25:47,801] Trial 40 finished with value: 0.2827413509808585 and parameters: {'n_estimators': 278, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_leaf_nodes': 12, 'class_weight': None}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:25:55,917] Trial 41 finished with value: 0.3162861435295859 and parameters: {'n_estimators': 294, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_leaf_nodes': 17, 'class_weight': 'balanced'}. Best is trial 15 with value: 0.3184573120356162.
[I 2026-07-28 18:26:03,057] Trial 42 finished with value: 0.32087089998479634 and parameters: {'n_estimators': 299, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_leaf_nodes': 15, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:26:11,835] Trial 43 finished with value: 0.31354740699433803 and parameters: {'n_estimators': 300, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_leaf_nodes': 15, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:26:22,092] Trial 44 finished with value: 0.31156198870336466 and parameters: {'n_estimators': 282, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_leaf_nodes': 19, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:26:26,335] Trial 45 finished with value: 0.3074487095987073 and parameters: {'n_estimators': 162, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_leaf_nodes': 21, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:26:33,410] Trial 46 finished with value: 0.29201238225213894 and parameters: {'n_estimators': 287, 'max_depth': 4, 'max_features': 0.8, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_leaf_nodes': 14, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:26:40,356] Trial 47 finished with value: 0.31175812299898964 and parameters: {'n_estimators': 273, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 5, 'max_leaf_nodes': 10, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:26:45,912] Trial 48 finished with value: 0.2957924058927848 and parameters: {'n_estimators': 220, 'max_depth': 3, 'max_features': 0.5, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_leaf_nodes': 25, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:26:52,724] Trial 49 finished with value: 0.3120362350412152 and parameters: {'n_estimators': 251, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_leaf_nodes': 12, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:27:00,882] Trial 50 finished with value: 0.3162861435295859 and parameters: {'n_estimators': 294, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_leaf_nodes': 16, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:27:08,244] Trial 51 finished with value: 0.31716939852250664 and parameters: {'n_estimators': 293, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_leaf_nodes': 17, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:27:15,630] Trial 52 finished with value: 0.31581655797427044 and parameters: {'n_estimators': 300, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_leaf_nodes': 18, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:27:22,787] Trial 53 finished with value: 0.3088055319497447 and parameters: {'n_estimators': 286, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_leaf_nodes': 19, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:27:29,975] Trial 54 finished with value: 0.3162861435295859 and parameters: {'n_estimators': 294, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_leaf_nodes': 14, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:27:37,328] Trial 55 finished with value: 0.3082950357362365 and parameters: {'n_estimators': 281, 'max_depth': 6, 'max_features': 0.5, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_leaf_nodes': 21, 'class_weight': 'balanced'}. Best is trial 42 with value: 0.32087089998479634.
[I 2026-07-28 18:27:44,762] Trial 56 finished with value: 0.32208272038914176 and parameters: {'n_estimators': 290, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_leaf_nodes': 35, 'class_weight': 'balanced'}. Best is trial 56 with value: 0.32208272038914176.
[I 2026-07-28 18:27:52,006] Trial 57 finished with value: 0.31515144484083446 and parameters: {'n_estimators': 272, 'max_depth': 4, 'max_features': 'sqrt', 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_leaf_nodes': 33, 'class_weight': 'balanced'}. Best is trial 56 with value: 0.32208272038914176.
[I 2026-07-28 18:27:59,534] Trial 58 finished with value: 0.2692549656667232 and parameters: {'n_estimators': 290, 'max_depth': 3, 'max_features': 'sqrt', 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_leaf_nodes': 40, 'class_weight': None}. Best is trial 56 with value: 0.32208272038914176.
[I 2026-07-28 18:28:05,804] Trial 59 finished with value: 0.3032618887396006 and parameters: {'n_estimators': 240, 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_leaf_nodes': 36, 'class_weight': 'balanced'}. Best is trial 56 with value: 0.32208272038914176.
[I 2026-07-28 18:28:12,122] Trial 60 finished with value: 0.3149229620410485 and parameters: {'n_estimators': 259, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_leaf_nodes': 13, 'class_weight': 'balanced'}. Best is trial 56 with value: 0.32208272038914176.
[I 2026-07-28 18:28:19,090] Trial 61 finished with value: 0.32178399043435124 and parameters: {'n_estimators': 284, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_leaf_nodes': 38, 'class_weight': 'balanced'}. Best is trial 56 with value: 0.32208272038914176.
[I 2026-07-28 18:28:26,129] Trial 62 finished with value: 0.31264521048995064 and parameters: {'n_estimators': 284, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_leaf_nodes': 36, 'class_weight': 'balanced'}. Best is trial 56 with value: 0.32208272038914176.
[I 2026-07-28 18:28:33,466] Trial 63 finished with value: 0.31634621181016376 and parameters: {'n_estimators': 300, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_leaf_nodes': 38, 'class_weight': 'balanced'}. Best is trial 56 with value: 0.32208272038914176.
[I 2026-07-28 18:28:40,476] Trial 64 finished with value: 0.3062846957540678 and parameters: {'n_estimators': 277, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 11, 'min_samples_leaf': 2, 'max_leaf_nodes': 38, 'class_weight': 'balanced'}. Best is trial 56 with value: 0.32208272038914176.
[I 2026-07-28 18:28:47,536] Trial 65 finished with value: 0.31734768245912515 and parameters: {'n_estimators': 290, 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_leaf_nodes': 31, 'class_weight': 'balanced'}. Best is trial 56 with value: 0.32208272038914176.

({'n_estimators': 290,
  'max_depth': 6,
  'max_features': 'sqrt',
  'min_samples_split': 12,
  'min_samples_leaf': 2,
  'max_leaf_nodes': 35,
  'class_weight': 'balanced'},
 0.32208272038914176)

### Linear Discriminant Analysis

In [16]:
def objective_lda(trial):
    params = {
    'solver': trial.suggest_categorical(
        'solver',
        ['lsqr', 'eigen']
    ),
    'shrinkage': trial.suggest_float(
        'shrinkage',
        0.01,
        0.5,
        log=True
    ),
    'store_covariance': False,
    'tol': trial.suggest_float(
        'tol',
        1e-4,
        1e-2,
        log=True
    )
    }

    model = Pipeline([
        ('scaler', StandardScaler()),
        ('clf', LinearDiscriminantAnalysis(**params))
    ])

    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=inner_cv,
        scoring='f1_macro'
    )

    mean_score = score.mean()
    std_score = score.std()

    return mean_score - alpha * std_score

In [17]:
study_lda = optuna.create_study(direction='maximize', sampler=sampler)
study_lda.optimize(objective_lda, n_trials=100)

study_lda.best_params, study_lda.best_value

[I 2026-07-28 18:32:38,158] A new study created in memory with name: no-name-938269b2-dfed-4458-982c-2f08bcde41c4
[I 2026-07-28 18:32:38,313] Trial 0 finished with value: 0.24606346759789394 and parameters: {'solver': 'lsqr', 'shrinkage': 0.06995363653959079, 'tol': 0.0003997206819121809}. Best is trial 0 with value: 0.24606346759789394.
[I 2026-07-28 18:32:38,440] Trial 1 finished with value: 0.24606346759789394 and parameters: {'solver': 'lsqr', 'shrinkage': 0.1085504227474508, 'tol': 0.0010124137770478635}. Best is trial 0 with value: 0.24606346759789394.
[I 2026-07-28 18:32:38,576] Trial 2 finished with value: 0.251598041291377 and parameters: {'solver': 'eigen', 'shrinkage': 0.34923398229690455, 'tol': 0.00030138649046798047}. Best is trial 2 with value: 0.251598041291377.
[I 2026-07-28 18:32:38,702] Trial 3 finished with value: 0.2531922726574767 and parameters: {'solver': 'eigen', 'shrinkage': 0.472705392113142, 'tol': 0.000304867088345807}. Best is trial 3 with value: 0.2531922726574767.
[I 2026-07-28 18:32:38,829] Trial 4 finished with value: 0.25788959374048603 and parameters: {'solver': 'eigen', 'shrinkage': 0.02533605885076776, 'tol': 0.0028604390429824616}. Best is trial 4 with value: 0.25788959374048603.
[I 2026-07-28 18:32:38,959] Trial 5 finished with value: 0.24606346759789394 and parameters: {'solver': 'eigen', 'shrinkage': 0.11921968649009668, 'tol': 0.0011790965486776312}. Best is trial 4 with value: 0.25788959374048603.
[I 2026-07-28 18:32:39,091] Trial 6 finished with value: 0.2565375564108044 and parameters: {'solver': 'eigen', 'shrinkage': 0.03507484078994472, 'tol': 0.00023606794572813083}. Best is trial 4 with value: 0.25788959374048603.
[I 2026-07-28 18:32:39,224] Trial 7 finished with value: 0.24684046334964105 and parameters: {'solver': 'eigen', 'shrinkage': 0.1416320452869399, 'tol': 0.00010793832090127293}. Best is trial 4 with value: 0.25788959374048603.
[I 2026-07-28 18:32:39,357] Trial 8 finished with value: 0.24606346759789394 and parameters: {'solver': 'lsqr', 'shrinkage': 0.12477547117579699, 'tol': 0.00022321987366901572}. Best is trial 4 with value: 0.25788959374048603.
[I 2026-07-28 18:32:39,492] Trial 9 finished with value: 0.25243421227942786 and parameters: {'solver': 'lsqr', 'shrinkage': 0.3903697468383558, 'tol': 0.00018838307787619773}. Best is trial 4 with value: 0.25788959374048603.
[I 2026-07-28 18:32:39,655] Trial 10 finished with value: 0.2573947153808809 and parameters: {'solver': 'eigen', 'shrinkage': 0.011612272421787738, 'tol': 0.0058728584632733}. Best is trial 4 with value: 0.25788959374048603.
[I 2026-07-28 18:32:39,814] Trial 11 finished with value: 0.2573947153808809 and parameters: {'solver': 'eigen', 'shrinkage': 0.012949712789284721, 'tol': 0.005931407447390307}. Best is trial 4 with value: 0.25788959374048603.
[I 2026-07-28 18:32:39,958] Trial 12 finished with value: 0.2573947153808809 and parameters: {'solver': 'eigen', 'shrinkage': 0.01050177447303268, 'tol': 0.006163799214318101}. Best is trial 4 with value: 0.25788959374048603.
[I 2026-07-28 18:32:40,106] Trial 13 finished with value: 0.26219617358696357 and parameters: {'solver': 'eigen', 'shrinkage': 0.021207656476477876, 'tol': 0.002634189060598553}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:40,230] Trial 14 finished with value: 0.25788959374048603 and parameters: {'solver': 'eigen', 'shrinkage': 0.02593398697380222, 'tol': 0.002579642684928737}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:40,368] Trial 15 finished with value: 0.25788959374048603 and parameters: {'solver': 'eigen', 'shrinkage': 0.02508227883441258, 'tol': 0.002677443679464434}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:40,491] Trial 16 finished with value: 0.251812035527589 and parameters: {'solver': 'eigen', 'shrinkage': 0.043982485347640814, 'tol': 0.002483575534618653}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:40,632] Trial 17 finished with value: 0.26116819578006156 and parameters: {'solver': 'eigen', 'shrinkage': 0.019664123100725458, 'tol': 0.0019396807724732172}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:40,757] Trial 18 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.017638663874900044, 'tol': 0.0006324182888149994}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:40,893] Trial 19 finished with value: 0.24687481306588088 and parameters: {'solver': 'eigen', 'shrinkage': 0.055546673842040276, 'tol': 0.009894876638324526}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:41,039] Trial 20 finished with value: 0.26116819578006156 and parameters: {'solver': 'eigen', 'shrinkage': 0.017060432091362633, 'tol': 0.0015280375556235909}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:41,170] Trial 21 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.015800233446673608, 'tol': 0.0006340071007324512}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:41,298] Trial 22 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.01863117809569549, 'tol': 0.0006708499814999282}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:41,422] Trial 23 finished with value: 0.2565375564108044 and parameters: {'solver': 'lsqr', 'shrinkage': 0.0353606105182637, 'tol': 0.0016028675998230294}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:41,553] Trial 24 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.02045655629424534, 'tol': 0.0006567421235489661}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:41,701] Trial 25 finished with value: 0.25923054235232884 and parameters: {'solver': 'lsqr', 'shrinkage': 0.03103650174187291, 'tol': 0.003978873726817349}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:41,855] Trial 26 finished with value: 0.251812035527589 and parameters: {'solver': 'lsqr', 'shrinkage': 0.04744576073654709, 'tol': 0.0018266898768985337}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:42,000] Trial 27 finished with value: 0.2573947153808809 and parameters: {'solver': 'eigen', 'shrinkage': 0.013127394619916806, 'tol': 0.0008024205443099222}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:42,119] Trial 28 finished with value: 0.26219617358696357 and parameters: {'solver': 'lsqr', 'shrinkage': 0.021244638620965175, 'tol': 0.004098817081421088}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:42,257] Trial 29 finished with value: 0.24606346759789394 and parameters: {'solver': 'lsqr', 'shrinkage': 0.08979988166269068, 'tol': 0.003559172447454607}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:42,387] Trial 30 finished with value: 0.24606346759789394 and parameters: {'solver': 'eigen', 'shrinkage': 0.06739086792830232, 'tol': 0.009196403530111722}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:42,511] Trial 31 finished with value: 0.25788959374048603 and parameters: {'solver': 'lsqr', 'shrinkage': 0.021365314441204247, 'tol': 0.00407567048611407}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:42,648] Trial 32 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.015247417752089818, 'tol': 0.0004711577471426544}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:42,773] Trial 33 finished with value: 0.25016319824796934 and parameters: {'solver': 'lsqr', 'shrinkage': 0.1973268760173753, 'tol': 0.0011782421097848346}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:42,907] Trial 34 finished with value: 0.25227339502706136 and parameters: {'solver': 'lsqr', 'shrinkage': 0.04002917250921104, 'tol': 0.0017677751938044448}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:43,051] Trial 35 finished with value: 0.25835128454998774 and parameters: {'solver': 'lsqr', 'shrinkage': 0.028632061610759093, 'tol': 0.00044247535221693634}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:43,182] Trial 36 finished with value: 0.25788959374048603 and parameters: {'solver': 'lsqr', 'shrinkage': 0.021911743197311533, 'tol': 0.0010367349537983039}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:43,317] Trial 37 finished with value: 0.2573947153808809 and parameters: {'solver': 'eigen', 'shrinkage': 0.01358118570934488, 'tol': 0.0032748167175689078}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:43,445] Trial 38 finished with value: 0.24687481306588088 and parameters: {'solver': 'eigen', 'shrinkage': 0.057744369245392564, 'tol': 0.001369434709592826}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:43,569] Trial 39 finished with value: 0.2573947153808809 and parameters: {'solver': 'lsqr', 'shrinkage': 0.010539809946897696, 'tol': 0.002132783493876582}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:43,708] Trial 40 finished with value: 0.2565375564108044 and parameters: {'solver': 'eigen', 'shrinkage': 0.03443537074637686, 'tol': 0.0008219215159020816}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:43,837] Trial 41 finished with value: 0.26116819578006156 and parameters: {'solver': 'eigen', 'shrinkage': 0.016791627755699225, 'tol': 0.001430135143445484}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:43,968] Trial 42 finished with value: 0.26116819578006156 and parameters: {'solver': 'eigen', 'shrinkage': 0.01800351520813917, 'tol': 0.0050826514911579326}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:44,100] Trial 43 finished with value: 0.25788959374048603 and parameters: {'solver': 'eigen', 'shrinkage': 0.023153257902987532, 'tol': 0.0018702190835391227}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:44,236] Trial 44 finished with value: 0.26001718744402574 and parameters: {'solver': 'eigen', 'shrinkage': 0.014866341219621732, 'tol': 0.0022243544805685186}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:44,378] Trial 45 finished with value: 0.25835128454998774 and parameters: {'solver': 'eigen', 'shrinkage': 0.0282034017381009, 'tol': 0.000338954393510866}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:44,502] Trial 46 finished with value: 0.251598041291377 and parameters: {'solver': 'eigen', 'shrinkage': 0.23984986670595493, 'tol': 0.004593413702602821}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:44,645] Trial 47 finished with value: 0.26116819578006156 and parameters: {'solver': 'eigen', 'shrinkage': 0.019872745633338885, 'tol': 0.0074697713671856986}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:44,779] Trial 48 finished with value: 0.2573947153808809 and parameters: {'solver': 'eigen', 'shrinkage': 0.012433522795194713, 'tol': 0.00328469027001242}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:44,906] Trial 49 finished with value: 0.25641262574234436 and parameters: {'solver': 'lsqr', 'shrinkage': 0.010002075654164867, 'tol': 0.0009007231419721532}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:45,034] Trial 50 finished with value: 0.25788959374048603 and parameters: {'solver': 'eigen', 'shrinkage': 0.025134072450790277, 'tol': 0.0001519843272319209}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:45,164] Trial 51 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.01641446826145587, 'tol': 0.0005659865758948606}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:45,297] Trial 52 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.017345646381329724, 'tol': 0.0011681234706894163}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:45,424] Trial 53 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.015097781246152048, 'tol': 0.0005414348294742127}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:45,557] Trial 54 finished with value: 0.2573947153808809 and parameters: {'solver': 'lsqr', 'shrinkage': 0.011570952889810157, 'tol': 0.000357757165107755}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:45,678] Trial 55 finished with value: 0.25923054235232884 and parameters: {'solver': 'lsqr', 'shrinkage': 0.0321378684508577, 'tol': 0.0006886432526024456}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:45,802] Trial 56 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.019026657797779057, 'tol': 0.0026900753416008996}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:45,931] Trial 57 finished with value: 0.25788959374048603 and parameters: {'solver': 'eigen', 'shrinkage': 0.023465928773812452, 'tol': 0.002264948157119627}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:46,054] Trial 58 finished with value: 0.25227339502706136 and parameters: {'solver': 'lsqr', 'shrinkage': 0.04053388149607911, 'tol': 0.0014246790482189506}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:46,187] Trial 59 finished with value: 0.25835128454998774 and parameters: {'solver': 'eigen', 'shrinkage': 0.026769986864348647, 'tol': 0.0015812779496551022}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:46,317] Trial 60 finished with value: 0.25931657090106675 and parameters: {'solver': 'lsqr', 'shrinkage': 0.013841857184785896, 'tol': 0.0002601635394580736}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:46,453] Trial 61 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.020539484768599535, 'tol': 0.00065553871500114}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:46,580] Trial 62 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.018693973785973633, 'tol': 0.0009671930834775987}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:46,706] Trial 63 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.016767343598556948, 'tol': 0.000570489533276262}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:46,831] Trial 64 finished with value: 0.25788959374048603 and parameters: {'solver': 'lsqr', 'shrinkage': 0.022564786128772663, 'tol': 0.000717219911803203}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:46,971] Trial 65 finished with value: 0.2573947153808809 and parameters: {'solver': 'lsqr', 'shrinkage': 0.012073762764242012, 'tol': 0.0004630801731987387}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:47,125] Trial 66 finished with value: 0.2573947153808809 and parameters: {'solver': 'lsqr', 'shrinkage': 0.013554655360157883, 'tol': 0.001176512529774301}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:47,268] Trial 67 finished with value: 0.24606346759789394 and parameters: {'solver': 'eigen', 'shrinkage': 0.09186554871725802, 'tol': 0.0004010848033794713}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:47,393] Trial 68 finished with value: 0.25923054235232884 and parameters: {'solver': 'lsqr', 'shrinkage': 0.030987193315434532, 'tol': 0.0030158057240231356}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:47,518] Trial 69 finished with value: 0.26116819578006156 and parameters: {'solver': 'eigen', 'shrinkage': 0.015151258881461765, 'tol': 0.003942115765337412}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:47,650] Trial 70 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.01909679970960636, 'tol': 0.0019308623269614761}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:47,783] Trial 71 finished with value: 0.26219617358696357 and parameters: {'solver': 'lsqr', 'shrinkage': 0.021059674518447122, 'tol': 0.0008339926563665861}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:47,915] Trial 72 finished with value: 0.25788959374048603 and parameters: {'solver': 'lsqr', 'shrinkage': 0.024712487338025824, 'tol': 0.0008036755967112527}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:48,052] Trial 73 finished with value: 0.26219617358696357 and parameters: {'solver': 'lsqr', 'shrinkage': 0.021017829840351766, 'tol': 0.0009653859122619205}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:48,178] Trial 74 finished with value: 0.25835128454998774 and parameters: {'solver': 'lsqr', 'shrinkage': 0.028446544753215657, 'tol': 0.0009952374602184148}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:48,327] Trial 75 finished with value: 0.25788959374048603 and parameters: {'solver': 'lsqr', 'shrinkage': 0.022128316971438678, 'tol': 0.0013039571999209792}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:48,462] Trial 76 finished with value: 0.26116819578006156 and parameters: {'solver': 'eigen', 'shrinkage': 0.016166771243733852, 'tol': 0.001648309045491813}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:48,590] Trial 77 finished with value: 0.2565375564108044 and parameters: {'solver': 'lsqr', 'shrinkage': 0.0365532577748067, 'tol': 0.0009166184681207139}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:48,719] Trial 78 finished with value: 0.26116819578006156 and parameters: {'solver': 'eigen', 'shrinkage': 0.019592888205005547, 'tol': 0.0011064117184915523}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:48,850] Trial 79 finished with value: 0.2573947153808809 and parameters: {'solver': 'lsqr', 'shrinkage': 0.011693754213025443, 'tol': 0.0007875835215188516}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:48,984] Trial 80 finished with value: 0.251812035527589 and parameters: {'solver': 'eigen', 'shrinkage': 0.04823899767209769, 'tol': 0.005378153152271063}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:49,113] Trial 81 finished with value: 0.26219617358696357 and parameters: {'solver': 'lsqr', 'shrinkage': 0.02113646347160477, 'tol': 0.0006150734319474632}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:49,248] Trial 82 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.02076533244783681, 'tol': 0.0005056703851875481}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:49,374] Trial 83 finished with value: 0.25788959374048603 and parameters: {'solver': 'lsqr', 'shrinkage': 0.026124159349777343, 'tol': 0.0007356961050268018}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:49,500] Trial 84 finished with value: 0.26001718744402574 and parameters: {'solver': 'lsqr', 'shrinkage': 0.01453021644454893, 'tol': 0.0019992832737655026}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:49,623] Trial 85 finished with value: 0.26116819578006156 and parameters: {'solver': 'lsqr', 'shrinkage': 0.01732984199539024, 'tol': 0.0005720017943985754}. Best is trial 13 with value: 0.26219617358696357.
[I 2026-07-28 18:32:49,756] Trial 86 finished with value: 0.25788959374048603 and parameters: {'solver': 'lsqr', 'shrinkage': 0.02354608580263444, 'tol': 0.002500706364320207}. Best is trial 13 with value: 0.26219617358696357.

({'solver': 'eigen',
  'shrinkage': 0.021207656476477876,
  'tol': 0.002634189060598553},
 0.26219617358696357)

### Support Vector Machine

In [18]:
def objective_svc(trial):
    params = {
        'C': trial.suggest_float('C', 0.01, 50.0, log=True),

        'kernel': trial.suggest_categorical(
            'kernel',
            ['linear', 'rbf']
        ),

        'gamma': trial.suggest_categorical(
            'gamma',
            ['scale', 'auto']
        ),

        'class_weight': trial.suggest_categorical(
            'class_weight',
            [None, 'balanced']
        ),

        'tol': trial.suggest_float(
            'tol',
            1e-5,
            1e-3,
            log=True
        ),

        'random_state': 42
    }

    model = Pipeline([
        ('scaler', StandardScaler()),
        ('clf', SVC(**params))
    ])

    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=inner_cv,
        scoring='f1_macro'
    )

    mean_score = score.mean()
    std_score = score.std()

    return mean_score - alpha * std_score

In [19]:
study_svc = optuna.create_study(direction='maximize', sampler=sampler)
study_svc.optimize(objective_svc, n_trials=100)

study_svc.best_params, study_svc.best_value

[I 2026-07-28 18:32:51,495] A new study created in memory with name: no-name-129031d5-3ffa-4ebc-b3b1-e251bf3d638a
[I 2026-07-28 18:32:51,642] Trial 0 finished with value: 0.1537997460371165 and parameters: {'C': 0.18263928656552764, 'kernel': 'rbf', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 0.00012894414393074176}. Best is trial 0 with value: 0.1537997460371165.
[I 2026-07-28 18:32:51,796] Trial 1 finished with value: 0.25505360023195073 and parameters: {'C': 0.9102519167536312, 'kernel': 'linear', 'gamma': 'auto', 'class_weight': None, 'tol': 4.993662066506419e-05}. Best is trial 1 with value: 0.25505360023195073.
[I 2026-07-28 18:32:51,931] Trial 2 finished with value: 0.297447403299175 and parameters: {'C': 4.844938633680331, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 0.0006267702540388485}. Best is trial 2 with value: 0.297447403299175.
[I 2026-07-28 18:32:52,066] Trial 3 finished with value: 0.22354488197264535 and parameters: {'C': 1.7505031694738118, 'kernel': 'rbf', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 0.00024198608614538694}. Best is trial 2 with value: 0.297447403299175.
[I 2026-07-28 18:32:52,192] Trial 4 finished with value: 0.2502922375533852 and parameters: {'C': 2.579794680369434, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': None, 'tol': 0.0004993980255757075}. Best is trial 2 with value: 0.297447403299175.
[I 2026-07-28 18:32:52,344] Trial 5 finished with value: 0.3069473237142106 and parameters: {'C': 2.7070131351207154, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 6.112170343513626e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:32:52,510] Trial 6 finished with value: 0.2912532082318563 and parameters: {'C': 19.93670809120284, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': None, 'tol': 0.00027855068482535877}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:32:52,638] Trial 7 finished with value: 0.25505360023195073 and parameters: {'C': 0.10928701063419977, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': None, 'tol': 5.4994264803456034e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:32:52,765] Trial 8 finished with value: 0.25505360023195073 and parameters: {'C': 0.011407055666413164, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': None, 'tol': 5.8910872811710225e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:36,340] Trial 9 finished with value: 0.25505360023195073 and parameters: {'C': 14.071131364849768, 'kernel': 'linear', 'gamma': 'auto', 'class_weight': None, 'tol': 1.5644186602631917e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:36,648] Trial 10 finished with value: 0.2957108251295676 and parameters: {'C': 49.543936795291856, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 1.013270721376279e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:36,790] Trial 11 finished with value: 0.2950243997478052 and parameters: {'C': 5.262232710918654, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 0.0007000043412471253}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:36,918] Trial 12 finished with value: 0.25103522660205396 and parameters: {'C': 0.27125576049967454, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 0.0009817169578682221}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:37,064] Trial 13 finished with value: 0.29311058972660853 and parameters: {'C': 9.261884162983765, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 2.3287971671125582e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:37,270] Trial 14 finished with value: 0.2990104345083458 and parameters: {'C': 3.6505011223378014, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 0.00013599128070651475}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:37,449] Trial 15 finished with value: 0.2519413848119519 and parameters: {'C': 0.5951858980831782, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 0.00014215093555747674}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:37,624] Trial 16 finished with value: 0.2363218139923492 and parameters: {'C': 0.03281015870067909, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 2.9044039616236952e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:37,809] Trial 17 finished with value: 0.28659476978135684 and parameters: {'C': 1.379151746065219, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 8.702367345069622e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:37,963] Trial 18 finished with value: 0.2534107514779649 and parameters: {'C': 0.36678911824833443, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 0.0002258873103491951}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:38,144] Trial 19 finished with value: 0.3069473237142106 and parameters: {'C': 2.687145723802348, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 3.3965624542257114e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:38,449] Trial 20 finished with value: 0.3010251492559756 and parameters: {'C': 36.79270351810106, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 2.5016262049914475e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:38,712] Trial 21 finished with value: 0.3037158581238526 and parameters: {'C': 30.80521770146161, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 3.2837947823748894e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:38,900] Trial 22 finished with value: 0.2933863978825705 and parameters: {'C': 7.758137772311742, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 3.635098505546398e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:39,108] Trial 23 finished with value: 0.2995240153049889 and parameters: {'C': 18.326074820087484, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 8.288754148311756e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:39,305] Trial 24 finished with value: 0.29603132887180655 and parameters: {'C': 2.167555232946133, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 1.6220037850997785e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:39,476] Trial 25 finished with value: 0.2747144990446276 and parameters: {'C': 0.7759072505050767, 'kernel': 'linear', 'gamma': 'scale', 'class_weight': 'balanced', 'tol': 3.965298274145651e-05}. Best is trial 5 with value: 0.3069473237142106.
[I 2026-07-28 18:33:39,652] Trial 26 finished with value: 0.3176607823781629 and parameters: {'C': 28.979140678844402, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 6.807837178093402e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:39,833] Trial 27 finished with value: 0.30671910692954846 and parameters: {'C': 8.398172753965433, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 6.584845574345617e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:40,011] Trial 28 finished with value: 0.2647591772365393 and parameters: {'C': 3.9268069185170154, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 1.942308043227255e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:40,197] Trial 29 finished with value: 0.1557511670161286 and parameters: {'C': 0.05681174078547287, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 9.906243963878747e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:40,399] Trial 30 finished with value: 0.2003632597425552 and parameters: {'C': 1.2077243765944168, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00016148499438140668}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:40,684] Trial 31 finished with value: 0.3039966428207838 and parameters: {'C': 9.066454710394865, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 7.270281456567158e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:40,905] Trial 32 finished with value: 0.3067927971742044 and parameters: {'C': 13.261614152812104, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 5.57658208797854e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:41,084] Trial 33 finished with value: 0.3143837682516311 and parameters: {'C': 24.498355763972548, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 4.475217846882244e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:41,301] Trial 34 finished with value: 0.3034820176737565 and parameters: {'C': 25.627388978120862, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 3.764726411249628e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:41,460] Trial 35 finished with value: 0.26629774584948623 and parameters: {'C': 5.577692130932158, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': None, 'tol': 4.5328004806620356e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:41,629] Trial 36 finished with value: 0.2455561711095625 and parameters: {'C': 2.2575911798296473, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00011433942783579415}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:41,827] Trial 37 finished with value: 0.2866498337663037 and parameters: {'C': 15.065269021016281, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': None, 'tol': 4.661517609496751e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:42,000] Trial 38 finished with value: 0.18869846660289025 and parameters: {'C': 0.4800542169942319, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 7.050938596695036e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:42,166] Trial 39 finished with value: 0.24947608224859646 and parameters: {'C': 3.0991991442454383, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': None, 'tol': 2.6279710940678358e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:42,337] Trial 40 finished with value: 0.16803715869335423 and parameters: {'C': 0.13431238409687776, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 1.1543244976370682e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:42,517] Trial 41 finished with value: 0.3122269514895567 and parameters: {'C': 11.466290110755667, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 5.5625875780635516e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:42,711] Trial 42 finished with value: 0.3176542677986337 and parameters: {'C': 49.001558982033174, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 4.777276564247986e-05}. Best is trial 26 with value: 0.3176607823781629.
[I 2026-07-28 18:33:42,919] Trial 43 finished with value: 0.3296254376281054 and parameters: {'C': 44.34812844053118, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 5.1433821825989694e-05}. Best is trial 43 with value: 0.3296254376281054.
[I 2026-07-28 18:33:43,172] Trial 44 finished with value: 0.3296254376281054 and parameters: {'C': 44.203703138582874, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 4.904180017409617e-05}. Best is trial 43 with value: 0.3296254376281054.
[I 2026-07-28 18:33:43,396] Trial 45 finished with value: 0.31939486713430687 and parameters: {'C': 47.34618690978172, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 4.4443445658813944e-05}. Best is trial 43 with value: 0.3296254376281054.
[I 2026-07-28 18:33:43,619] Trial 46 finished with value: 0.33439095564992144 and parameters: {'C': 43.03381132143013, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 9.574362409933795e-05}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:43,860] Trial 47 finished with value: 0.2948664058519363 and parameters: {'C': 34.2076992922033, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': None, 'tol': 0.00018620092525910474}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:44,079] Trial 48 finished with value: 0.3176542677986337 and parameters: {'C': 49.144857352863625, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00010761599046519581}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:44,286] Trial 49 finished with value: 0.3094518461463125 and parameters: {'C': 20.433096654960107, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00042045189423129916}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:44,502] Trial 50 finished with value: 0.3206560762689803 and parameters: {'C': 34.172456455826996, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 8.41883970056074e-05}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:44,712] Trial 51 finished with value: 0.31339804313862 and parameters: {'C': 33.391112451911454, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 8.313074516687082e-05}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:44,911] Trial 52 finished with value: 0.30989166668708484 and parameters: {'C': 19.69826021544766, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 9.559175090039006e-05}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:45,100] Trial 53 finished with value: 0.3176542677986337 and parameters: {'C': 49.96534262447297, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00012205871662052186}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:45,333] Trial 54 finished with value: 0.3070466026518673 and parameters: {'C': 27.244706788633845, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 6.579655761349775e-05}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:45,567] Trial 55 finished with value: 0.3219298645030761 and parameters: {'C': 39.27567935671017, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 8.051314307113035e-05}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:45,874] Trial 56 finished with value: 0.3219298645030761 and parameters: {'C': 38.54812662997093, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.0001501422967115566}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:46,140] Trial 57 finished with value: 0.2912532082318563 and parameters: {'C': 19.955018022974222, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': None, 'tol': 0.0002872983622739907}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:46,388] Trial 58 finished with value: 0.31793324418609786 and parameters: {'C': 36.7025830966054, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00021233468019277898}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:46,563] Trial 59 finished with value: 0.30451289838296397 and parameters: {'C': 14.909327523306, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00017331961274880318}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:46,745] Trial 60 finished with value: 0.32192041030972607 and parameters: {'C': 37.97498722406474, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.0001552238355754541}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:46,926] Trial 61 finished with value: 0.32192041030972607 and parameters: {'C': 38.197553759440645, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.0001461987324120338}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:47,126] Trial 62 finished with value: 0.31385906075817294 and parameters: {'C': 22.91448698543933, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00013974397554421524}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:47,364] Trial 63 finished with value: 0.29219426128297715 and parameters: {'C': 6.254348333678736, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00030704701910599583}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:47,561] Trial 64 finished with value: 0.3219298645030761 and parameters: {'C': 39.730343093665475, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00014900653453417298}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:47,838] Trial 65 finished with value: 0.3122269514895567 and parameters: {'C': 11.16965087688494, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00020036684915238559}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:48,108] Trial 66 finished with value: 0.13859334852921007 and parameters: {'C': 0.013583570335975455, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.0003604906393958431}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:48,354] Trial 67 finished with value: 0.2962300387260015 and parameters: {'C': 17.41576045884862, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00025611996399326593}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:48,586] Trial 68 finished with value: 0.3076462077404137 and parameters: {'C': 25.323638641271423, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00012728119349495037}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:48,827] Trial 69 finished with value: 0.3219298645030761 and parameters: {'C': 39.814905815675665, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 9.706426901178655e-05}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:49,052] Trial 70 finished with value: 0.3247590448985165 and parameters: {'C': 40.68202369609712, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 9.670856201505033e-05}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:49,283] Trial 71 finished with value: 0.3247590448985165 and parameters: {'C': 40.38055838569218, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 9.86211376241659e-05}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:49,529] Trial 72 finished with value: 0.3176607823781629 and parameters: {'C': 29.836308623132304, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 7.67062491676313e-05}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:49,791] Trial 73 finished with value: 0.30127485907860563 and parameters: {'C': 16.219913530138147, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 0.00011294789113015797}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:50,043] Trial 74 finished with value: 0.3034820176737565 and parameters: {'C': 26.35622609664789, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 6.19248401411428e-05}. Best is trial 46 with value: 0.33439095564992144.
[I 2026-07-28 18:33:50,270] Trial 75 finished with value: 0.3088403266245869 and parameters: {'C': 12.179352747835921, 'kernel': 'rbf', 'gamma': 'auto', 'class_weight': 'balanced', 'tol': 9.146257119670707e-05}. Best is trial 46 with value: 0.33439095564992144.

({'C': 42.74192629343276,
  'kernel': 'rbf',
  'gamma': 'auto',
  'class_weight': 'balanced',
  'tol': 1.7446341387960417e-05},
 0.33770276178659125)

### XGBoost

In [20]:
def objective_xgb(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 2, 4),

        'learning_rate': trial.suggest_float(
            'learning_rate',
            0.01,
            0.1,
            log=True
        ),

        'n_estimators': trial.suggest_int('n_estimators', 100, 300),

        'min_child_weight': trial.suggest_float(
            'min_child_weight',
            1.0,
            10.0
        ),

        'gamma': trial.suggest_float(
            'gamma',
            0.0,
            0.5
        ),

        'subsample': trial.suggest_float(
            'subsample',
            0.7,
            1.0
        ),

        'colsample_bytree': trial.suggest_float(
            'colsample_bytree',
            0.7,
            1.0
        ),

        'reg_lambda': trial.suggest_float(
            'reg_lambda',
            0.5,
            10.0,
            log=True
        ),

        'reg_alpha': trial.suggest_float(
            'reg_alpha',
            0.0,
            0.5
        ),

        'max_delta_step': trial.suggest_int(
            'max_delta_step',
            0,
            5
        ),

        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',
        'random_state': 42,
        'n_jobs': -1
    }

    model = Pipeline([
        ('clf', XGBClassifier(**params))
    ])

    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=inner_cv,
        scoring='f1_macro'
    )

    mean_score = score.mean()
    std_score = score.std()

    return mean_score - alpha * std_score

In [21]:
study_xgb = optuna.create_study(direction='maximize', sampler=sampler)
study_xgb.optimize(objective_xgb, n_trials=100)

study_xgb.best_params, study_xgb.best_value

[I 2026-07-28 18:33:57,002] A new study created in memory with name: no-name-d1051682-8b1b-4ce7-922f-6d46620b73ea
[I 2026-07-28 18:33:59,324] Trial 0 finished with value: 0.27455707712660754 and parameters: {'max_depth': 3, 'learning_rate': 0.09773584004575739, 'n_estimators': 128, 'min_child_weight': 5.664966871273631, 'gamma': 0.4386865359639777, 'subsample': 0.9222305853262613, 'colsample_bytree': 0.9091047222985804, 'reg_lambda': 4.101312569988357, 'reg_alpha': 0.17974557560987758, 'max_delta_step': 1}. Best is trial 0 with value: 0.27455707712660754.
[I 2026-07-28 18:34:04,125] Trial 1 finished with value: 0.2476468796670265 and parameters: {'max_depth': 4, 'learning_rate': 0.06458228319438214, 'n_estimators': 274, 'min_child_weight': 9.219164973008242, 'gamma': 0.2556711994304689, 'subsample': 0.8504548884061598, 'colsample_bytree': 0.9394885536900326, 'reg_lambda': 3.5042297663646855, 'reg_alpha': 0.3509834386288517, 'max_delta_step': 4}. Best is trial 0 with value: 0.27455707712660754.
[I 2026-07-28 18:34:07,731] Trial 2 finished with value: 0.2830147516432116 and parameters: {'max_depth': 4, 'learning_rate': 0.02177685487188668, 'n_estimators': 175, 'min_child_weight': 1.845837458567821, 'gamma': 0.289140070498087, 'subsample': 0.7107826821390226, 'colsample_bytree': 0.8396794054397381, 'reg_lambda': 2.54077935007182, 'reg_alpha': 0.1432706260641422, 'max_delta_step': 3}. Best is trial 2 with value: 0.2830147516432116.
[I 2026-07-28 18:34:11,725] Trial 3 finished with value: 0.25875650137688944 and parameters: {'max_depth': 2, 'learning_rate': 0.010898034759198191, 'n_estimators': 265, 'min_child_weight': 4.241715772701366, 'gamma': 0.06353025632594239, 'subsample': 0.8566729780164413, 'colsample_bytree': 0.9309980659295832, 'reg_lambda': 0.9544641808072379, 'reg_alpha': 0.31144523790950013, 'max_delta_step': 0}. Best is trial 2 with value: 0.2830147516432116.
[I 2026-07-28 18:34:14,735] Trial 4 finished with value: 0.27224952354175663 and parameters: {'max_depth': 2, 'learning_rate': 0.033990271344210995, 'n_estimators': 208, 'min_child_weight': 6.736869113483859, 'gamma': 0.3630456668613308, 'subsample': 0.9927556238387604, 'colsample_bytree': 0.8548901044903585, 'reg_lambda': 1.31566724604786, 'reg_alpha': 0.39759309738435183, 'max_delta_step': 1}. Best is trial 2 with value: 0.2830147516432116.
[I 2026-07-28 18:34:18,273] Trial 5 finished with value: 0.2525490308635017 and parameters: {'max_depth': 3, 'learning_rate': 0.011979987953345747, 'n_estimators': 105, 'min_child_weight': 9.663835732101326, 'gamma': 0.4179900602561029, 'subsample': 0.9087922618281093, 'colsample_bytree': 0.8226858833242809, 'reg_lambda': 0.8402937103342152, 'reg_alpha': 0.07821852133554302, 'max_delta_step': 1}. Best is trial 2 with value: 0.2830147516432116.
[I 2026-07-28 18:34:21,607] Trial 6 finished with value: 0.28404924203996906 and parameters: {'max_depth': 3, 'learning_rate': 0.05183175602578894, 'n_estimators': 232, 'min_child_weight': 3.5194050725134858, 'gamma': 0.47743264033159705, 'subsample': 0.9213690750087306, 'colsample_bytree': 0.8663062157534202, 'reg_lambda': 3.12490662060915, 'reg_alpha': 0.20980003121389496, 'max_delta_step': 1}. Best is trial 6 with value: 0.28404924203996906.
[I 2026-07-28 18:34:23,801] Trial 7 finished with value: 0.27893983201260647 and parameters: {'max_depth': 3, 'learning_rate': 0.05725931002475599, 'n_estimators': 102, 'min_child_weight': 2.0446537645622462, 'gamma': 0.023001321010876374, 'subsample': 0.712218640695691, 'colsample_bytree': 0.9566381752033022, 'reg_lambda': 4.115759469440884, 'reg_alpha': 0.2370869145436626, 'max_delta_step': 0}. Best is trial 6 with value: 0.28404924203996906.
[I 2026-07-28 18:34:26,430] Trial 8 finished with value: 0.26408921919023925 and parameters: {'max_depth': 3, 'learning_rate': 0.029748958838287345, 'n_estimators': 134, 'min_child_weight': 4.904664843141758, 'gamma': 0.19925236719868672, 'subsample': 0.884755029415665, 'colsample_bytree': 0.8905280952602931, 'reg_lambda': 0.5726798202504277, 'reg_alpha': 0.1873063073132356, 'max_delta_step': 3}. Best is trial 6 with value: 0.28404924203996906.
[I 2026-07-28 18:34:30,620] Trial 9 finished with value: 0.3208384140699011 and parameters: {'max_depth': 3, 'learning_rate': 0.0718604348929872, 'n_estimators': 232, 'min_child_weight': 2.466409843732867, 'gamma': 0.03528437370021492, 'subsample': 0.8927257834618947, 'colsample_bytree': 0.7079533931624865, 'reg_lambda': 2.891223107907126, 'reg_alpha': 0.4701151207124788, 'max_delta_step': 3}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:34:34,476] Trial 10 finished with value: 0.2568660432663109 and parameters: {'max_depth': 2, 'learning_rate': 0.07546808482982567, 'n_estimators': 297, 'min_child_weight': 7.314990715841436, 'gamma': 0.13219196478812334, 'subsample': 0.7831560105722907, 'colsample_bytree': 0.7033452722084869, 'reg_lambda': 8.904996510392667, 'reg_alpha': 0.49309419610145955, 'max_delta_step': 5}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:34:37,268] Trial 11 finished with value: 0.28501708690965577 and parameters: {'max_depth': 3, 'learning_rate': 0.042951489636760716, 'n_estimators': 223, 'min_child_weight': 3.2871573989960052, 'gamma': 0.49376760963416605, 'subsample': 0.9678870537841364, 'colsample_bytree': 0.7688053822989542, 'reg_lambda': 1.8544435011475198, 'reg_alpha': 0.467637299461488, 'max_delta_step': 2}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:34:41,338] Trial 12 finished with value: 0.3116886872709055 and parameters: {'max_depth': 4, 'learning_rate': 0.040205718860802264, 'n_estimators': 231, 'min_child_weight': 2.9358417102953114, 'gamma': 0.1295248060266222, 'subsample': 0.9818912461602712, 'colsample_bytree': 0.7200983069712662, 'reg_lambda': 1.7847555499379475, 'reg_alpha': 0.4436049854340323, 'max_delta_step': 2}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:34:44,682] Trial 13 finished with value: 0.2499588778279566 and parameters: {'max_depth': 4, 'learning_rate': 0.02141395028612431, 'n_estimators': 173, 'min_child_weight': 2.449001563339574, 'gamma': 0.12573378747168423, 'subsample': 0.7977736778373083, 'colsample_bytree': 0.7139703748533661, 'reg_lambda': 6.690025754097809, 'reg_alpha': 0.4245981805427787, 'max_delta_step': 4}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:34:48,255] Trial 14 finished with value: 0.31022689385819513 and parameters: {'max_depth': 4, 'learning_rate': 0.09948749176608458, 'n_estimators': 248, 'min_child_weight': 2.990290871699586, 'gamma': 0.09986768847166394, 'subsample': 0.9691586853910436, 'colsample_bytree': 0.7603626958357427, 'reg_lambda': 1.7085613357782783, 'reg_alpha': 0.3045318350174069, 'max_delta_step': 2}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:34:52,394] Trial 15 finished with value: 0.2900945454154822 and parameters: {'max_depth': 4, 'learning_rate': 0.03978587215649859, 'n_estimators': 187, 'min_child_weight': 1.0044690399141936, 'gamma': 0.01124734536150878, 'subsample': 0.8028000235528424, 'colsample_bytree': 0.7594398490726414, 'reg_lambda': 5.991025571514463, 'reg_alpha': 0.4115819192787609, 'max_delta_step': 3}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:34:56,336] Trial 16 finished with value: 0.2948461483813689 and parameters: {'max_depth': 4, 'learning_rate': 0.02676433070886253, 'n_estimators': 208, 'min_child_weight': 4.181105210692109, 'gamma': 0.19884295065785354, 'subsample': 0.959895289197346, 'colsample_bytree': 0.8033441053083265, 'reg_lambda': 1.3655062116518943, 'reg_alpha': 0.3390495814542984, 'max_delta_step': 4}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:34:59,567] Trial 17 finished with value: 0.2598947605366693 and parameters: {'max_depth': 2, 'learning_rate': 0.01573822386991625, 'n_estimators': 247, 'min_child_weight': 1.222027073515875, 'gamma': 0.18618474342873267, 'subsample': 0.998620646697089, 'colsample_bytree': 0.7299453714233737, 'reg_lambda': 2.414615902365738, 'reg_alpha': 0.4969044567247382, 'max_delta_step': 2}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:03,885] Trial 18 finished with value: 0.2834703623570002 and parameters: {'max_depth': 3, 'learning_rate': 0.0707167304216335, 'n_estimators': 298, 'min_child_weight': 5.778124334441665, 'gamma': 0.06506774192988711, 'subsample': 0.8895371231034894, 'colsample_bytree': 0.9850681464615738, 'reg_lambda': 5.243641758489486, 'reg_alpha': 0.4381711353569482, 'max_delta_step': 5}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:06,450] Trial 19 finished with value: 0.2969412368093304 and parameters: {'max_depth': 3, 'learning_rate': 0.04705497597335694, 'n_estimators': 160, 'min_child_weight': 4.246009624146653, 'gamma': 0.1681429366716894, 'subsample': 0.9385696578232993, 'colsample_bytree': 0.793043132802902, 'reg_lambda': 1.140953562709873, 'reg_alpha': 0.007318254390041107, 'max_delta_step': 3}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:09,852] Trial 20 finished with value: 0.3010493081533957 and parameters: {'max_depth': 4, 'learning_rate': 0.035613645159576296, 'n_estimators': 227, 'min_child_weight': 2.645169182774148, 'gamma': 0.320398301698097, 'subsample': 0.7624679691110249, 'colsample_bytree': 0.7435205804683216, 'reg_lambda': 1.9012180511830024, 'reg_alpha': 0.38130407473884287, 'max_delta_step': 2}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:12,837] Trial 21 finished with value: 0.319524724906145 and parameters: {'max_depth': 4, 'learning_rate': 0.0929374072228391, 'n_estimators': 252, 'min_child_weight': 2.8876324194450382, 'gamma': 0.09534515764853221, 'subsample': 0.9616539941466934, 'colsample_bytree': 0.700109400582271, 'reg_lambda': 1.7858020826690288, 'reg_alpha': 0.3022315534576685, 'max_delta_step': 2}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:16,398] Trial 22 finished with value: 0.31213517878644925 and parameters: {'max_depth': 4, 'learning_rate': 0.08082716905457094, 'n_estimators': 271, 'min_child_weight': 1.818139640762194, 'gamma': 0.06701617156832607, 'subsample': 0.9476247970771108, 'colsample_bytree': 0.7007787776823239, 'reg_lambda': 2.617134050431411, 'reg_alpha': 0.27914044987204406, 'max_delta_step': 2}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:19,750] Trial 23 finished with value: 0.3070520509971825 and parameters: {'max_depth': 4, 'learning_rate': 0.0797704582451626, 'n_estimators': 273, 'min_child_weight': 1.6248739529831178, 'gamma': 0.06127393779333609, 'subsample': 0.9465795458280247, 'colsample_bytree': 0.7026085509743193, 'reg_lambda': 2.7144804478865447, 'reg_alpha': 0.3061096225018746, 'max_delta_step': 3}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:23,299] Trial 24 finished with value: 0.31647218646240843 and parameters: {'max_depth': 4, 'learning_rate': 0.08203653873415744, 'n_estimators': 253, 'min_child_weight': 3.4342207586068243, 'gamma': 0.01279566521641673, 'subsample': 0.888671184036872, 'colsample_bytree': 0.7481423132468998, 'reg_lambda': 3.4327038788466178, 'reg_alpha': 0.2633760572365611, 'max_delta_step': 4}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:26,059] Trial 25 finished with value: 0.3104023304356459 and parameters: {'max_depth': 3, 'learning_rate': 0.06148448169208542, 'n_estimators': 249, 'min_child_weight': 3.5057909343228744, 'gamma': 0.013717204916485735, 'subsample': 0.8760944807911799, 'colsample_bytree': 0.7393904320138278, 'reg_lambda': 4.1833049007654814, 'reg_alpha': 0.26037090645857686, 'max_delta_step': 4}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:28,985] Trial 26 finished with value: 0.29476089659159765 and parameters: {'max_depth': 4, 'learning_rate': 0.08806950409454453, 'n_estimators': 256, 'min_child_weight': 4.81099101764411, 'gamma': 0.0049277280671715384, 'subsample': 0.8218507832039346, 'colsample_bytree': 0.7839577835262972, 'reg_lambda': 3.3088740123052305, 'reg_alpha': 0.14601559545456505, 'max_delta_step': 5}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:31,823] Trial 27 finished with value: 0.31719754383366583 and parameters: {'max_depth': 3, 'learning_rate': 0.05155419262464089, 'n_estimators': 287, 'min_child_weight': 3.737367268828994, 'gamma': 0.1072430802781986, 'subsample': 0.9030848786514311, 'colsample_bytree': 0.7389037006998588, 'reg_lambda': 2.0493586077116746, 'reg_alpha': 0.36478015687331794, 'max_delta_step': 4}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:36,146] Trial 28 finished with value: 0.28797719001903377 and parameters: {'max_depth': 3, 'learning_rate': 0.055348807670031586, 'n_estimators': 285, 'min_child_weight': 6.555090133914748, 'gamma': 0.09526284879662014, 'subsample': 0.9206183974878825, 'colsample_bytree': 0.7281018073991443, 'reg_lambda': 1.5062116364829847, 'reg_alpha': 0.3651265008775021, 'max_delta_step': 3}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:39,178] Trial 29 finished with value: 0.30629283945479163 and parameters: {'max_depth': 3, 'learning_rate': 0.09936662773548521, 'n_estimators': 214, 'min_child_weight': 5.354527029262926, 'gamma': 0.231920667987916, 'subsample': 0.9059737914517891, 'colsample_bytree': 0.8154675958290487, 'reg_lambda': 0.592324496128934, 'reg_alpha': 0.3861904935692946, 'max_delta_step': 1}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:43,468] Trial 30 finished with value: 0.31576400479058175 and parameters: {'max_depth': 2, 'learning_rate': 0.06682814061924401, 'n_estimators': 286, 'min_child_weight': 2.3419844803323517, 'gamma': 0.1595351839959672, 'subsample': 0.8269031538826649, 'colsample_bytree': 0.764166333068928, 'reg_lambda': 2.12696518816975, 'reg_alpha': 0.33322792547848656, 'max_delta_step': 4}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:47,244] Trial 31 finished with value: 0.31614935992768206 and parameters: {'max_depth': 3, 'learning_rate': 0.08522806504110934, 'n_estimators': 239, 'min_child_weight': 3.7999677377087893, 'gamma': 0.05213032179047314, 'subsample': 0.8684187275271713, 'colsample_bytree': 0.7442536101157409, 'reg_lambda': 4.706971888030312, 'reg_alpha': 0.24153757620022426, 'max_delta_step': 4}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:50,706] Trial 32 finished with value: 0.2612341465361785 and parameters: {'max_depth': 3, 'learning_rate': 0.06896853393937878, 'n_estimators': 263, 'min_child_weight': 8.218760202579695, 'gamma': 0.09744363207165962, 'subsample': 0.9046658334052592, 'colsample_bytree': 0.7812671472564747, 'reg_lambda': 3.2865369244370752, 'reg_alpha': 0.280996826462602, 'max_delta_step': 4}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:55,751] Trial 33 finished with value: 0.3004276456782795 and parameters: {'max_depth': 4, 'learning_rate': 0.048915827517395406, 'n_estimators': 283, 'min_child_weight': 2.807977899678978, 'gamma': 0.03853149749270578, 'subsample': 0.8372862621457885, 'colsample_bytree': 0.7469021564944419, 'reg_lambda': 2.2087989525240013, 'reg_alpha': 0.21322952900611497, 'max_delta_step': 5}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:35:59,532] Trial 34 finished with value: 0.3163803872021349 and parameters: {'max_depth': 3, 'learning_rate': 0.06225389564328841, 'n_estimators': 259, 'min_child_weight': 4.009967785538846, 'gamma': 0.0882574648619779, 'subsample': 0.8489589860446612, 'colsample_bytree': 0.7187648404106415, 'reg_lambda': 2.900497051512345, 'reg_alpha': 0.3440402917742346, 'max_delta_step': 3}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:36:02,932] Trial 35 finished with value: 0.3126851690313511 and parameters: {'max_depth': 4, 'learning_rate': 0.0890038012029129, 'n_estimators': 198, 'min_child_weight': 4.760558344069526, 'gamma': 0.02814736891491032, 'subsample': 0.9348989064670411, 'colsample_bytree': 0.729023218272293, 'reg_lambda': 3.7118440014118894, 'reg_alpha': 0.4573575570570301, 'max_delta_step': 4}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:36:06,217] Trial 36 finished with value: 0.31376085533608744 and parameters: {'max_depth': 4, 'learning_rate': 0.07604462936650079, 'n_estimators': 240, 'min_child_weight': 3.2079163068298846, 'gamma': 0.24041566403720802, 'subsample': 0.894642942892951, 'colsample_bytree': 0.776044336071149, 'reg_lambda': 0.8860815448178256, 'reg_alpha': 0.14631210717752163, 'max_delta_step': 3}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:36:10,056] Trial 37 finished with value: 0.2840490870740147 and parameters: {'max_depth': 3, 'learning_rate': 0.05738375216722573, 'n_estimators': 278, 'min_child_weight': 5.6132360616335735, 'gamma': 0.14104379267141062, 'subsample': 0.8614186306335904, 'colsample_bytree': 0.8325699338715258, 'reg_lambda': 1.1173585081850133, 'reg_alpha': 0.27750025752056795, 'max_delta_step': 5}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:36:13,019] Trial 38 finished with value: 0.30534397327129015 and parameters: {'max_depth': 2, 'learning_rate': 0.09049688382983452, 'n_estimators': 216, 'min_child_weight': 2.218261486135873, 'gamma': 0.08376349335720346, 'subsample': 0.9258723853976634, 'colsample_bytree': 0.8891811140124788, 'reg_lambda': 2.2368385340635397, 'reg_alpha': 0.31841780581203316, 'max_delta_step': 3}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:36:16,635] Trial 39 finished with value: 0.3029057939089288 and parameters: {'max_depth': 3, 'learning_rate': 0.06722459960699653, 'n_estimators': 266, 'min_child_weight': 1.4585113267563932, 'gamma': 0.2757920447516246, 'subsample': 0.9120910452363263, 'colsample_bytree': 0.7520668697542439, 'reg_lambda': 1.4493444372323614, 'reg_alpha': 0.3624427366175451, 'max_delta_step': 1}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:36:20,918] Trial 40 finished with value: 0.30488524602830747 and parameters: {'max_depth': 3, 'learning_rate': 0.05101144137740232, 'n_estimators': 255, 'min_child_weight': 3.6971876093478606, 'gamma': 0.03834576261833095, 'subsample': 0.8834371659362223, 'colsample_bytree': 0.7164040786402107, 'reg_lambda': 3.7983061598197634, 'reg_alpha': 0.11064870799075077, 'max_delta_step': 4}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:36:24,506] Trial 41 finished with value: 0.30536763581077475 and parameters: {'max_depth': 2, 'learning_rate': 0.060982819570233666, 'n_estimators': 261, 'min_child_weight': 4.276960019850695, 'gamma': 0.1142867834589175, 'subsample': 0.8488777094180053, 'colsample_bytree': 0.7129247017997697, 'reg_lambda': 2.8879361582466636, 'reg_alpha': 0.3483650494951107, 'max_delta_step': 3}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:36:28,410] Trial 42 finished with value: 0.31081905618845035 and parameters: {'max_depth': 3, 'learning_rate': 0.07561302614943015, 'n_estimators': 239, 'min_child_weight': 4.088220358795668, 'gamma': 0.07606827262145549, 'subsample': 0.8516145222661213, 'colsample_bytree': 0.7323692585365894, 'reg_lambda': 2.913559660735878, 'reg_alpha': 0.22374754164645744, 'max_delta_step': 2}. Best is trial 9 with value: 0.3208384140699011.
[I 2026-07-28 18:36:32,942] Trial 43 finished with value: 0.3169282206361836 and parameters: {'max_depth': 3, 'learning_rate': 0.06143575918337225, 'n_estimators': 296, 'min_child_weight': 3.248391981590113, 'gamma': 0.002884612423681654, 'subsample': 0.8679699344721639, 'colsample_bytree': 0.721110375707184, 'reg_lambda': 2.0888142534613157, 'reg_alpha': 0.39235991932660486, 'max_delta_step': 3}. Best is trial 9 with value: 0.3208384140699011.

({'max_depth': 2,
  'learning_rate': 0.06716855319447462,
  'n_estimators': 256,
  'min_child_weight': 3.5029541229805456,
  'gamma': 0.036663587078571896,
  'subsample': 0.9531484458357324,
  'colsample_bytree': 0.8097002223699291,
  'reg_lambda': 1.4656211064879527,
  'reg_alpha': 0.3573644422502141,
  'max_delta_step': 3},
 0.32595585272471317)

## Validation Set Metrics

In [22]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

In [23]:
models_val = {
    'Logistic Regression': Pipeline([
        ('scaler', StandardScaler()),
        ('clf', LogisticRegression(**study_lr.best_params)),
    ]),

    'Random Forest': RandomForestClassifier(**study_rf.best_params),

    'LDA': Pipeline([
        ('scaler', StandardScaler()),
        ('clf', LinearDiscriminantAnalysis(**study_lda.best_params)),
    ]),

    'SVC': Pipeline([
        ('scaler', StandardScaler()),
        ('clf', SVC(**study_svc.best_params)),
    ]),

    'XGBoost': XGBClassifier(**study_xgb.best_params)
}

In [24]:
val_predictions = {}
val_metrics = {}
val_reports ={}

for model_name, model in models_val.items():

    model.fit(X_train, y_train)

    val_predictions[model_name] = model.predict(X_val)

    val_metrics[model_name] = {
        'Accuracy': accuracy_score(y_val, val_predictions[model_name]),
        'Precision': precision_score(y_val, val_predictions[model_name], average='weighted', zero_division=0),
        'Recall': recall_score(y_val, val_predictions[model_name], average='weighted', zero_division=0),
        'F1': f1_score(y_val, val_predictions[model_name], average='weighted', zero_division=0),
    }

    val_reports[model_name] = classification_report(y_val, val_predictions[model_name], zero_division=0)

### Summary Metrics

In [25]:
df_val_metrics = pd.DataFrame(val_metrics)
df_val_metrics.T.sort_values(by='Accuracy', ascending=False)

                     Accuracy  Precision    Recall        F1
XGBoost              0.733333   0.669333  0.733333  0.682284
LDA                  0.633333   0.401111  0.633333  0.491156
Random Forest        0.633333   0.633810  0.633333  0.632479
SVC                  0.466667   0.528889  0.466667  0.491068
Logistic Regression  0.266667   0.421329  0.266667  0.276781

### Classification Report

In [26]:
for model_names, reports in val_reports.items():
    print(f'{model_names}:\n {reports} \n -------------------------------------------------------')

Logistic Regression:
               precision    recall  f1-score   support

           0       0.08      0.33      0.12         3
           1       0.50      0.16      0.24        19
           2       0.36      0.50      0.42         8

    accuracy                           0.27        30
   macro avg       0.31      0.33      0.26        30
weighted avg       0.42      0.27      0.28        30

 -------------------------------------------------------
Random Forest:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.70      0.74      0.72        19
           2       0.71      0.62      0.67         8

    accuracy                           0.63        30
   macro avg       0.47      0.45      0.46        30
weighted avg       0.63      0.63      0.63        30

 -------------------------------------------------------
LDA:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.63      1.00      0.78        19
           2       0.00      0.00      0.00         8

    accuracy                           0.63        30
   macro avg       0.21      0.33      0.26        30
weighted avg       0.40      0.63      0.49        30

 -------------------------------------------------------
SVC:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.67      0.53      0.59        19
           2       0.40      0.50      0.44         8

    accuracy                           0.47        30
   macro avg       0.36      0.34      0.34        30
weighted avg       0.53      0.47      0.49        30

 -------------------------------------------------------
XGBoost:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.72      0.95      0.82        19
           2       0.80      0.50      0.62         8

    accuracy                           0.73        30
   macro avg       0.51      0.48      0.48        30
weighted avg       0.67      0.73      0.68        30

 -------------------------------------------------------

## Test Set Metrics

In [27]:
X_combined = np.concatenate([X_train, X_val], axis=0)
y_combined = np.concatenate([y_train, y_val], axis=0)

In [28]:
final_model = XGBClassifier(**study_xgb.best_params)
final_model.fit(X_combined, y_combined)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8097002223699291, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, feature_weights=None,
              gamma=0.036663587078571896, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.06716855319447462, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None, max_delta_step=3,
              max_depth=2, max_leaves=None, min_child_weight=3.5029541229805456,
              missing=nan, monotone_constraints=None, multi_strategy=None,
              n_estimators=256, n_jobs=None, num_parallel_tree=None, ...)

In [29]:
test_predictions = final_model.predict(X_test)

test_metrics = {
    'Model': 'XGBoost',
    'Accuracy': accuracy_score(y_test, test_predictions),
    'Precision': precision_score(y_test, test_predictions, average='weighted', zero_division=0),
    'Recall': recall_score(y_test, test_predictions, average='weighted', zero_division=0),
    'F1': f1_score(y_test, test_predictions, average='weighted', zero_division=0),
}

### Summary Metrics

In [30]:
df_test_metrics = pd.DataFrame([test_metrics])
df_test_metrics

     Model  Accuracy  Precision    Recall        F1
0  XGBoost  0.533333   0.533333  0.533333  0.533333

### Classification Report

In [31]:
print(classification_report(y_test, test_predictions))

              precision    recall  f1-score   support

           0       0.33      0.33      0.33         3
           1       0.68      0.68      0.68        19
           2       0.25      0.25      0.25         8

    accuracy                           0.53        30
   macro avg       0.42      0.42      0.42        30
weighted avg       0.53      0.53      0.53        30